import type { Technician, InstallationTypeConfig, QueueBooking, PenaltyRecord, TimeSlot } from './types';

export const INITIAL_INSTALLATION_TYPES: InstallationTypeConfig[] = [
  {
    id: 'inst-built-kitchen',
    name: 'งานติดตั้งครัว Built-in Master (ชุดใหญ่)',
    category: 'Built-in Furniture',
    minSkillLevel: 3,
    requiredTeamSize: 3,
    estDurationHours: 6,
    description: 'ประกอบตู้ Built-in, หินท็อปครัว, งานเจาะท่อดูดควัน และปรับระดับบานตู้ไฮกวน',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
  },
  {
    id: 'inst-built-closet',
    name: 'งานติดตั้งตู้เสื้อผ้า Walk-in Closet',
    category: 'Built-in Furniture',
    minSkillLevel: 2,
    requiredTeamSize: 2,
    estDurationHours: 4,
    description: 'ติดตั้งโครงตู้เสื้อผ้า Built-in อะลูมิเนียม หน้าบานกระจก และไฟ LED ซ่อนตู้',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
  },
  {
    id: 'inst-flooring-laminate',
    name: 'งานปูพื้น SPC / Laminate (50-100 ตร.ม.)',
    category: 'Flooring & Tile',
    minSkillLevel: 2,
    requiredTeamSize: 2,
    estDurationHours: 4,
    description: 'ปรับระดับพื้น ปูแผ่นรองกันความชื้น และติดตั้งแผ่น SPC พร้อมบัวพื้นรอบห้อง',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
  },
  {
    id: 'inst-smart-home',
    name: 'งานติดตั้งระบบ Smart Home & Digital Door Lock',
    category: 'Electrical & Smart Home',
    minSkillLevel: 2,
    requiredTeamSize: 1,
    estDurationHours: 2,
    description: 'เจาะประตูติดตั้ง Digital Lock, สวิตช์ไฟอัจฉริยะ และเซ็ตอัประบบ Gateway',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
  },
  {
    id: 'inst-aircon-multi',
    name: 'งานติดตั้งเครื่องปรับอากาศ Multi-Split 3 เครื่อง',
    category: 'Air Condition & HVAC',
    minSkillLevel: 3,
    requiredTeamSize: 2,
    estDurationHours: 5,
    description: 'เดินท่อน้ำยาคอมเพรสเซอร์ภายนอก แขวนคอยล์เย็น และทดสอบแรงดันระบบน้ำยา R32',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
  },
  {
    id: 'inst-curtains-motor',
    name: 'งานติดตั้งผ้าม่านมอเตอร์ไฟฟ้า + วอลเปเปอร์',
    category: 'Curtains & Wallpaper',
    minSkillLevel: 1,
    requiredTeamSize: 2,
    estDurationHours: 3,
    description: 'ติดตั้งรางม่านไฟฟ้า ต่อสายสัญญาณ และปูวอลเปเปอร์ไวนิลเกรดพรีเมียม',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
  },
];

export const SERVICE_ZONES = [
  'Zone 1: กรุงเทพฯ (สุขุมวิท - บางนา - ประเวศ)',
  'Zone 2: นนทบุรี (ราชพฤกษ์ - แจ้งวัฒนะ - บางบัวทอง)',
  'Zone 3: ปทุมธานี (รังสิต - ลำลูกกา - คลองหลวง)',
  'Zone 4: สมุทรปราการ (เทพารักษ์ - ศรีนครินทร์ - สำโรง)',
];

export const AVAILABLE_TIME_SLOTS: TimeSlot[] = [
  { id: 'slot-am-1', startTime: '09:00', endTime: '12:00', period: 'Morning' },
  { id: 'slot-pm-1', startTime: '13:00', endTime: '17:00', period: 'Afternoon' },
  { id: 'slot-fd-1', startTime: '09:00', endTime: '17:00', period: 'Full Day' },
];

export const INITIAL_TECHNICIANS: Technician[] = [
  {
    id: 'tech-01',
    code: 'T-GOLD-01',
    name: 'ทีมช่างสมชาย & ทีม (ช่างใหญ่ Built-in)',
    phone: '081-987-6543',
    avatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&q=80&w=150',
    tier: 'Gold',
    rating: 4.95,
    completedJobs: 142,
    penaltyPoints: 0,
    activePenaltiesCount: 0,
    primaryZone: 'Zone 1: กรุงเทพฯ (สุขุมวิท - บางนา - ประเวศ)',
    secondaryZones: ['Zone 4: สมุทรปราการ (เทพารักษ์ - ศรีนครินทร์ - สำโรง)'],
    skills: [
      { category: 'Built-in Furniture', level: 3, isCertified: true },
      { category: 'Electrical & Smart Home', level: 2, isCertified: true },
      { category: 'Flooring & Tile', level: 2, isCertified: true },
    ],
    dailyCapacityHours: 8,
    bookedHoursToday: 2,
    status: 'Available',
  },
  {
    id: 'tech-02',
    code: 'T-GOLD-02',
    name: 'ทีมช่างวิชัย อินสทอลเลอร์ (ช่างแอร์ & ไฟฟ้า)',
    phone: '089-123-4567',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    tier: 'Gold',
    rating: 4.88,
    completedJobs: 118,
    penaltyPoints: 5,
    activePenaltiesCount: 0,
    primaryZone: 'Zone 2: นนทบุรี (ราชพฤกษ์ - แจ้งวัฒนะ - บางบัวทอง)',
    secondaryZones: ['Zone 3: ปทุมธานี (รังสิต - ลำลูกกา - คลองหลวง)'],
    skills: [
      { category: 'Air Condition & HVAC', level: 3, isCertified: true },
      { category: 'Electrical & Smart Home', level: 3, isCertified: true },
      { category: 'Plumbing & Sanitary', level: 2, isCertified: true },
    ],
    dailyCapacityHours: 8,
    bookedHoursToday: 5,
    status: 'Available',
  },
  {
    id: 'tech-03',
    code: 'T-SILV-03',
    name: 'ทีมช่างประเสริฐการช่าง (ช่างปูพื้น SPC & งานไม้)',
    phone: '086-555-4321',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
    tier: 'Silver',
    rating: 4.65,
    completedJobs: 84,
    penaltyPoints: 15,
    activePenaltiesCount: 1,
    primaryZone: 'Zone 1: กรุงเทพฯ (สุขุมวิท - บางนา - ประเวศ)',
    secondaryZones: ['Zone 2: นนทบุรี (ราชพฤกษ์ - แจ้งวัฒนะ - บางบัวทอง)'],
    skills: [
      { category: 'Flooring & Tile', level: 3, isCertified: true },
      { category: 'Built-in Furniture', level: 2, isCertified: false },
    ],
    dailyCapacityHours: 8,
    bookedHoursToday: 4,
    status: 'Available',
  },
  {
    id: 'tech-04',
    code: 'T-SILV-04',
    name: 'ทีมช่างอนันต์ & เดอะแก๊ง (งานผ้าม่าน & วอลเปเปอร์)',
    phone: '083-444-9988',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150',
    tier: 'Silver',
    rating: 4.70,
    completedJobs: 65,
    penaltyPoints: 10,
    activePenaltiesCount: 0,
    primaryZone: 'Zone 3: ปทุมธานี (รังสิต - ลำลูกกา - คลองหลวง)',
    secondaryZones: ['Zone 2: นนทบุรี (ราชพฤกษ์ - แจ้งวัฒนะ - บางบัวทอง)'],
    skills: [
      { category: 'Curtains & Wallpaper', level: 2, isCertified: true },
      { category: 'Electrical & Smart Home', level: 1, isCertified: true },
    ],
    dailyCapacityHours: 8,
    bookedHoursToday: 0,
    status: 'Available',
  },
  {
    id: 'tech-05',
    code: 'T-PEN-05',
    name: 'ทีมช่างกิตติพงษ์ (ติด Cooldown จาก Penalty E-CN)',
    phone: '082-888-1122',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=150',
    tier: 'Cooldown',
    rating: 4.20,
    completedJobs: 45,
    penaltyPoints: 45,
    activePenaltiesCount: 2,
    primaryZone: 'Zone 4: สมุทรปราการ (เทพารักษ์ - ศรีนครินทร์ - สำโรง)',
    secondaryZones: ['Zone 1: กรุงเทพฯ (สุขุมวิท - บางนา - ประเวศ)'],
    skills: [
      { category: 'Built-in Furniture', level: 2, isCertified: true },
      { category: 'Flooring & Tile', level: 1, isCertified: false },
    ],
    dailyCapacityHours: 8,
    bookedHoursToday: 0,
    status: 'In Cooldown',
  },
];

export const INITIAL_BOOKINGS: QueueBooking[] = [
  {
    id: 'bk-1001',
    bookingRef: 'BK-2026-0723-01',
    customerName: 'คุณภิญโญ รัตนประเสริฐ',
    customerPhone: '089-888-7766',
    addressZone: 'Zone 1: กรุงเทพฯ (สุขุมวิท - บางนา - ประเวศ)',
    installationTypeId: 'inst-built-kitchen',
    installationTypeName: 'งานติดตั้งครัว Built-in Master (ชุดใหญ่)',
    requiredSkillLevel: 3,
    assignedTechTeamId: 'tech-01',
    assignedTechTeamName: 'ทีมช่างสมชาย & ทีม (ช่างใหญ่ Built-in)',
    bookingDate: '2026-07-24',
    timeSlot: '09:00 - 17:00 (Full Day)',
    status: 'Dispatched to KANNA',
    createdFrom: 'Selling Tools (E-ordering)',
    createdAt: '2026-07-23 08:30',
  },
  {
    id: 'bk-1002',
    bookingRef: 'BK-2026-0723-02',
    customerName: 'คุณสิรินทร์ วงศ์อนันต์',
    customerPhone: '081-333-2211',
    addressZone: 'Zone 2: นนทบุรี (ราชพฤกษ์ - แจ้งวัฒนะ - บางบัวทอง)',
    installationTypeId: 'inst-aircon-multi',
    installationTypeName: 'งานติดตั้งเครื่องปรับอากาศ Multi-Split 3 เครื่อง',
    requiredSkillLevel: 3,
    assignedTechTeamId: 'tech-02',
    assignedTechTeamName: 'ทีมช่างวิชัย อินสทอลเลอร์ (ช่างแอร์ & ไฟฟ้า)',
    bookingDate: '2026-07-24',
    timeSlot: '13:00 - 17:00 (Afternoon)',
    status: 'STS In-Progress',
    createdFrom: 'Selling Tools (E-ordering)',
    createdAt: '2026-07-23 09:15',
  },
  {
    id: 'bk-1003',
    bookingRef: 'BK-2026-0723-03',
    customerName: 'คุณณัฐพล เดชอนันต์',
    customerPhone: '084-777-6655',
    addressZone: 'Zone 1: กรุงเทพฯ (สุขุมวิท - บางนา - ประเวศ)',
    installationTypeId: 'inst-flooring-laminate',
    installationTypeName: 'งานปูพื้น SPC / Laminate (50-100 ตร.ม.)',
    requiredSkillLevel: 2,
    assignedTechTeamId: 'tech-03',
    assignedTechTeamName: 'ทีมช่างประเสริฐการช่าง (ช่างปูพื้น SPC & งานไม้)',
    bookingDate: '2026-07-25',
    timeSlot: '09:00 - 12:00 (Morning)',
    status: 'Scheduled',
    createdFrom: 'COOHOM Direct',
    createdAt: '2026-07-23 10:00',
  },
  {
    id: 'bk-1004',
    bookingRef: 'BK-2026-0723-04',
    customerName: 'คุณพรพิมล เมธากุล',
    customerPhone: '086-111-9900',
    addressZone: 'Zone 4: สมุทรปราการ (เทพารักษ์ - ศรีนครินทร์ - สำโรง)',
    installationTypeId: 'inst-built-closet',
    installationTypeName: 'งานติดตั้งตู้เสื้อผ้า Walk-in Closet',
    requiredSkillLevel: 2,
    assignedTechTeamId: 'tech-05',
    assignedTechTeamName: 'ทีมช่างกิตติพงษ์',
    bookingDate: '2026-07-22',
    timeSlot: '09:00 - 17:00 (Full Day)',
    status: 'Penalty E-CN Issued',
    createdFrom: 'Manual POS',
    createdAt: '2026-07-22 14:00',
    penaltyRef: 'ECN-2026-0722-09',
  },
];

export const INITIAL_PENALTIES: PenaltyRecord[] = [
  {
    id: 'pen-901',
    eCnNumber: 'ECN-2026-0722-09',
    bookingRef: 'BK-2026-0722-04',
    techId: 'tech-05',
    techName: 'ทีมช่างกิตติพงษ์',
    violationType: 'QC Defect / Failed Review',
    fineAmountTHB: 3500,
    scoreDeduction: 25,
    tierImpact: 'ปรับลดจาก Silver $\\rightarrow$ Cooldown (พักการจ่ายคิวงาน 7 วัน)',
    issuedAt: '2026-07-22 17:30',
    status: 'Active Penalty',
    details: 'งานประกอบโครงตู้ Walk-in Closet ไม่ได้ระดับ ฉากเอียง 5 องศา และบานตู้ตก QC ตรวจพบรอยขูดขีดบนแผงไม้',
  },
  {
    id: 'pen-902',
    eCnNumber: 'ECN-2026-0715-02',
    bookingRef: 'BK-2026-0715-11',
    techId: 'tech-03',
    techName: 'ทีมช่างประเสริฐการช่าง',
    violationType: 'Late Arrival (SLA Breach)',
    fineAmountTHB: 1000,
    scoreDeduction: 10,
    tierImpact: 'หักคะแนน Queue Priority อัตโนมัติ 15%',
    issuedAt: '2026-07-15 11:00',
    status: 'Resolved / Fine Paid',
    details: 'เข้าหน้างานล่าช้ากว่าเวลานัดหมาย 1 ชั่วโมง 45 นาที โดยไม่ได้แจ้งล่วงหน้าผ่านระบบ KANNA/STS',
  },
];
