import type { Technician, InstallationTypeConfig, QueueBooking, PenaltyRecord, TimeSlot, Branch, Zone, Skill, UserAccount, StandardCostItem } from './types';
import { generate200Technicians } from './generateTechs';

export const INITIAL_BRANCHES: Branch[] = [
  { id: 'br-01', code: 'B01', name: 'สาขาพระราม 9', province: 'กรุงเทพมหานคร', status: 'Active' },
  { id: 'br-02', code: 'B02', name: 'สาขาเอกมัย-รามอินทรา', province: 'กรุงเทพมหานคร', status: 'Active' },
  { id: 'br-03', code: 'B03', name: 'สาขาราชพฤกษ์', province: 'นนทบุรี', status: 'Active' },
  { id: 'br-04', code: 'B04', name: 'สาขาบางนา', province: 'สมุทรปราการ', status: 'Active' },
  {
    id: 'br-st-60016',
    code: 'B16',
    name: 'สาขาภูเก็ต เฟสติวัล',
    province: 'ภูเก็ต',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาภูเก็ต เฟสติวัล)",
    address: "79 หมู่ 5 ตำบลวิชิต  อำเภอเมืองภูเก็ต จังหวัดภูเก็ต 83000",
    openTime: '08:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 7.89241854, longitude: 98.37053226
  },
  {
    id: 'br-st-60020',
    code: 'B20',
    name: 'สาขาศรีสมาน',
    province: 'นนทบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (ศรีสมาน)",
    address: "320 ม.3 ตำบลบ้านใหม่ อำเภอปากเกร็ด จังหวัดนนทบุรี 11120",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.93872141, longitude: 100.5457731
  },
  {
    id: 'br-st-60022',
    code: 'B22',
    name: 'สาขาบางแสน',
    province: 'ชลบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (บางแสน)",
    address: "87 หมู่ 4 ตำบลห้วยกะปิ อำเภอเมืองชลบุรี จังหวัดชลบุรี 20130",
    openTime: '07:30',
    closeTime: '20:30',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.31034516, longitude: 100.9558477
  },
  {
    id: 'br-st-60023',
    code: 'B23',
    name: 'สาขารังสิต คลอง4',
    province: 'ปทุมธานี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (รังสิต คลอง4)",
    address: "70 หมู่ 2 ตำบลบึงยี่โถ อำเภอธัญบุรี จังหวัดปทุมธานี 12130",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.99887196, longitude: 100.6756767
  },
  {
    id: 'br-st-60024',
    code: 'B24',
    name: 'สาขาภูเก็ต ฉลอง',
    province: 'ภูเก็ต',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาภูเก็ต ฉลอง)",
    address: "10/52 หมู่ 1 ตำบลฉลอง อำเภอเมืองภูเก็ต จังหวัดภูเก็ต 83130",
    openTime: '08:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 7.84872631, longitude: 98.34990273
  },
  {
    id: 'br-st-60025',
    code: 'B25',
    name: 'สาขาเมืองเอก',
    province: 'ปทุมธานี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาเมืองเอก)",
    address: "298 หมู่ 13  ถนนพหลโยธิน ตำบลคูคต อำเภอลำลูกกา จังหวัดปทุมธานี 12130",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.96715221, longitude: 100.6180959
  },
  {
    id: 'br-st-60026',
    code: 'B26',
    name: 'สาขาสมุทรปราการ',
    province: 'สมุทรปราการ',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาสมุทรปราการ)",
    address: "6 หมู่ 7 ตำบลบางเมือง อำเภอเมืองสมุทรปราการ จังหวัดสมุทรปราการ 10270",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.61183764, longitude: 100.6158879
  },
  {
    id: 'br-st-60027',
    code: 'B27',
    name: 'สาขาเชียงใหม่ สันทราย',
    province: 'เชียงใหม่',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาเชียงใหม่ สันทราย)",
    address: "552 หมู่ 4 ตำบลสันทรายน้อย อำเภอสันทราย จังหวัดเชียงใหม่ 50210",
    openTime: '08:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 18.83794641, longitude: 99.03194256
  },
  {
    id: 'br-st-60028',
    code: 'B28',
    name: 'สาขาบางใหญ่',
    province: 'นนทบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาบางใหญ่)",
    address: "29 หมู่ 2 ตำบลปลายบาง อำเภอบางกรวย จังหวัดนนทบุรี 11130",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.80612896, longitude: 100.4098226
  },
  {
    id: 'br-st-60029',
    code: 'B29',
    name: 'สาขานครอินทร์',
    province: 'นนทบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขานครอินทร์)",
    address: "30/4 หมู่ 3 ตำบลบางไผ่ อำเภอเมืองนนทบุรี จังหวัดนนทบุรี 11130",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.8277705, longitude: 100.4867818
  },
  {
    id: 'br-st-60030',
    code: 'B30',
    name: 'สาขาอุดรธานี กุดสระ',
    province: 'อุดรธานี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาอุดรธานี กุดสระ)",
    address: "11/1 หมู่ 6 ตำบลกุดสระ อำเภอเมืองอุดรธานี จังหวัดอุดรธานี 41000",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 17.46503, longitude: 102.79532
  },
  {
    id: 'br-st-60031',
    code: 'B31',
    name: 'สาขาพระราม 3',
    province: 'กรุงเทพมหานคร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาพระราม 3)",
    address: "572 ถนนพระราม 3 แขวงบางโพงพาง เขตยานนาวา กรุงเทพมหานคร 10120",
    openTime: '07:00',
    closeTime: '22:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.68312428, longitude: 100.5228373
  },
  {
    id: 'br-st-60032',
    code: 'B32',
    name: 'สาขารัตนาธิเบศร์',
    province: 'นนทบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขารัตนาธิเบศร์)",
    address: "405/4 ถนนรัตนาธิเบศร์  ตำบลบางกระสอ อำเภอเมืองนนทบุรี จังหวัดนนทบุรี 11000",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.865607, longitude: 100.49245
  },
  {
    id: 'br-st-61600',
    code: 'B600',
    name: 'สาขาแพร่',
    province: 'แพร่',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาแพร่)",
    address: "227 หมู่ 8 ตำบลนาจักร อำเภอเมืองแพร่ จังหวัดแพร่ 54000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 18.11197662, longitude: 100.1432377
  },
  {
    id: 'br-st-61601',
    code: 'B601',
    name: 'สาขากาฬสินธุ์',
    province: 'กาฬสินธุ์',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด สาขากาฬสินธุ์",
    address: "22 ถนนเลี่ยงเมืองหัวคู ตำบลกาฬสินธุ์ อำเภอเมืองกาฬสินธุ์ จังหวัดกาฬสินธุ์ 46000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 16.45591442, longitude: 103.5444439
  },
  {
    id: 'br-st-61602',
    code: 'B602',
    name: 'สาขานครนายก',
    province: 'นครนายก',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด สาขานครนายก",
    address: "1-111/6 ถนนเขาทุเรียน ตำบลนครนายก อำเภอเมืองนครนายก จังหวัดนครนายก 26000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.2111729, longitude: 101.22256605
  },
  {
    id: 'br-st-61604',
    code: 'B604',
    name: 'สาขาราชบุรี',
    province: 'ราชบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด สาขาราชบุรี",
    address: "189 หมู่ที่ 9  ตำบลพงสวาย อำเภอเมืองราชบุรี จังหวัดราชบุรี 70000",
    openTime: '08.00',
    closeTime: '19.00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.554566, longitude: 99.829415
  },
  {
    id: 'br-st-60918',
    code: 'B918',
    name: 'สาขาบางบัวทอง',
    province: 'นนทบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาบางบัวทอง)",
    address: "59/9 หมู่ 1 ตำบลบางบัวทอง  อำเภอบางบัวทอง จังหวัดนนทบุรี  11110",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.92873898, longitude: 100.4130362
  },
  {
    id: 'br-st-60919',
    code: 'B919',
    name: 'สาขาสุขาภิบาล 3',
    province: 'กรุงเทพมหานคร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาสุขาภิบาล 3)",
    address: "252 ถนนรามคำแหง  แขวงมีนบุรี  เขตมีนบุรี จังหวัดกรุงเทพมหานคร  10510",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.81089258, longitude: 100.7358813
  },
  {
    id: 'br-st-60920',
    code: 'B920',
    name: 'สาขาบางนา',
    province: 'สมุทรปราการ',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาบางนา)",
    address: "54 หมู่ที่ 13  ตำบลบางแก้ว อำเภอบางพลี จังหวัดสมุทรปราการ 10540",
    openTime: '06:00',
    closeTime: '22:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.65177169, longitude: 100.676675
  },
  {
    id: 'br-st-60921',
    code: 'B921',
    name: 'สาขาพิษณุโลก',
    province: 'พิษณุโลก',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาพิษณุโลก)",
    address: "788 หมู่ที่ 10 ตำบลสมอแข  อำเภอเมืองพิษณุโลก จังหวัดพิษณุโลก 65000",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 16.81517804, longitude: 100.3331312
  },
  {
    id: 'br-st-60922',
    code: 'B922',
    name: 'สาขาสุรินทร์',
    province: 'สุรินทร์',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาสุรินทร์)",
    address: "322 หมู่ 2 ตำบลนอกเมือง  อำเภอเมืองสุรินทร์ จังหวัดสุรินทร์  32000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.86402154, longitude: 103.5234623
  },
  {
    id: 'br-st-60923',
    code: 'B923',
    name: 'สาขาลำปาง',
    province: 'ลำปาง',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาลำปาง)",
    address: "70 ถนนไฮเวย์-ลำปาง-งาว  ตำบลชมพู อำเภอเมืองลำปาง  จังหวัดลำปาง 52100",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 18.26870436, longitude: 99.47658157
  },
  {
    id: 'br-st-60924',
    code: 'B924',
    name: 'สาขาบุรีรัมย์',
    province: 'บุรีรัมย์',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาบุรีรัมย์)",
    address: "55 หมู่ที่ 1  ตำบลบ้านบัว อำเภอเมืองบุรีรัมย์  จังหวัดบุรีรัมย์ 31000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.95644689, longitude: 103.0537967
  },
  {
    id: 'br-st-60925',
    code: 'B925',
    name: 'สาขามหาชัย',
    province: 'สมุทรสาคร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขามหาชัย)",
    address: "5/5 หมู่ที่ 3  ตำบลนาดี อำเภอเมืองสมุทรสาคร จังหวัดสมุทรสาคร 74000",
    openTime: '07:00',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.58038932, longitude: 100.3039165
  },
  {
    id: 'br-st-60926',
    code: 'B926',
    name: 'สาขาสกลนคร',
    province: 'สกลนคร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาสกลนคร)",
    address: "333 หมู่ 15  ตำบลห้วยยาง อำเภอเมืองสกลนคร จังหวัดสกลนคร 47000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 17.14168398, longitude: 104.1036424
  },
  {
    id: 'br-st-60927',
    code: 'B927',
    name: 'สาขาสุราษฏร์ธานี',
    province: 'สุราษฎร์ธานี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาสุราษฏร์ธานี)",
    address: "43 หมู่ 1  ตำบลท่าทองใหม่ อำเภอกาญจนดิษฐ์ จังหวัดสุราษฎร์ธานี  84290",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 9.14940402, longitude: 99.39883303
  },
  {
    id: 'br-st-60928',
    code: 'B928',
    name: 'สาขาขอนแก่น',
    province: 'ขอนแก่น',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาขอนแก่น)",
    address: "224 หมู่ 1  ตำบลสำราญ อำเภอเมืองขอนแก่น จังหวัดขอนแก่น 40000",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 16.52389131, longitude: 102.8305246
  },
  {
    id: 'br-st-60929',
    code: 'B929',
    name: 'สาขาลพบุรี',
    province: 'ลพบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาลพบุรี)",
    address: "555 หมู่ที่ 4  ตำบลกกโก อำเภอเมืองลพบุรี จังหวัดลพบุรี 15000",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.77372429, longitude: 100.6949192
  },
  {
    id: 'br-st-60930',
    code: 'B930',
    name: 'สาขาชะอำ',
    province: 'เพชรบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาชะอำ)",
    address: "829 ถนนเพชรเกษม(บ่อแขม)  ตำบลชะอำ อำเภอชะอำ จังหวัดเพชรบุรี 76120",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 12.72932978, longitude: 99.95490687
  },
  {
    id: 'br-st-60931',
    code: 'B931',
    name: 'สาขาหาดใหญ่',
    province: 'สงขลา',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาหาดใหญ่)",
    address: "1119 หมู่ 1  ถนนเลี่ยงเมือง(สายเอเชีย) ตำบลควนลัง อำเภอหาดใหญ่ จังหวัดสงขลา 90110",
    openTime: '07:00',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 6.98583549, longitude: 100.4304642
  },
  {
    id: 'br-st-60932',
    code: 'B932',
    name: 'สาขาจันทบุรี',
    province: 'จันทบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาจันทบุรี)",
    address: "999 หมู่ 2  ตำบลท่าช้าง อำเภอเมืองจันทบุรี จังหวัดจันทบุรี 22000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 12.66119207, longitude: 102.0766656
  },
  {
    id: 'br-st-60933',
    code: 'B933',
    name: 'สาขาอุบลราชธานี',
    province: 'อุบลราชธานี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาอุบลราชธานี)",
    address: "267 หมู่ที่ 7  ตำบลแจระแม อำเภอเมืองอุบลราชธานี  จังหวัดอุบลราชธานี 34000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 15.23281896, longitude: 104.8234513
  },
  {
    id: 'br-st-60934',
    code: 'B934',
    name: 'สาขาเชียงใหม่',
    province: 'เชียงใหม่',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาเชียงใหม่)",
    address: "111 หมู่ 1  ตำบลไชยสถาน  อำเภอสารภี จังหวัดเชียงใหม่ 50140",
    openTime: '07:30',
    closeTime: '19:30',
    phone: '1308',
    storeGroup: 'TWD', latitude: 18.72124195, longitude: 99.04309673
  },
  {
    id: 'br-st-60935',
    code: 'B935',
    name: 'สาขาร้อยเอ็ด',
    province: 'ร้อยเอ็ด',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาร้อยเอ็ด)",
    address: "444 หมู่ที่ 7  ตำบลดงลาน อำเภอเมืองร้อยเอ็ด จังหวัดร้อยเอ็ด 45000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 16.05627927, longitude: 103.6230278
  },
  {
    id: 'br-st-60936',
    code: 'B936',
    name: 'สาขาสุพรรณบุรี',
    province: 'สุพรรณบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาสุพรรณบุรี)",
    address: "77/7 หมู่ที่  4 ตำบลสนามชัย อำเภอเมืองสุพรรณบุรี  จังหวัดสุพรรณบุรี 72000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.47673037, longitude: 100.1334891
  },
  {
    id: 'br-st-60937',
    code: 'B937',
    name: 'สาขากาญจนบุรี',
    province: 'กาญจนบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขากาญจนบุรี)",
    address: "111 หมู่ที่ 9 ตำบลปากแพรก อำเภอเมืองกาญจนบุรี  จังหวัดกาญจนบุรี 71000",
    openTime: '07:30',
    closeTime: '19:30',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.02035954, longitude: 99.55510873
  },
  {
    id: 'br-st-60938',
    code: 'B938',
    name: 'สาขาฉะเชิงเทรา',
    province: 'ฉะเชิงเทรา',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาฉะเชิงเทรา)",
    address: "99 หมู่ที่ 2 ตำบลโสธร  อำเภอเมืองฉะเชิงเทรา จังหวัดฉะเชิงเทรา 24000",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.66431305, longitude: 101.047541
  },
  {
    id: 'br-st-60939',
    code: 'B939',
    name: 'สาขาระยอง',
    province: 'ระยอง',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาระยอง)",
    address: "999/9 หมู่ที่ 1 ตำบลเชิงเนิน  อำเภอเมืองระยอง  จังหวัดระยอง 21000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 12.67172067, longitude: 101.3038375
  },
  {
    id: 'br-st-60940',
    code: 'B940',
    name: 'สาขาเพชรบูรณ์',
    province: 'เพชรบูรณ์',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาเพชรบูรณ์)",
    address: "40 หมู่ 5 ตำบลบ้านโตก อำเภอเมืองเพชรบูรณ์  จังหวัดเพชรบูรณ์ 67000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 16.3751652, longitude: 101.1195685
  },
  {
    id: 'br-st-60941',
    code: 'B941',
    name: 'สาขาศาลายา',
    province: 'นครปฐม',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาศาลายา)",
    address: "8 หมู่ 1 ตำบลทรงคนอง อำเภอสามพราน  จังหวัดนครปฐม 73210",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.78694774, longitude: 100.2728405
  },
  {
    id: 'br-st-60942',
    code: 'B942',
    name: 'สาขามหาสารคาม',
    province: 'มหาสารคาม',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขามหาสารคาม)",
    address: "303 หมู่ 11  ตำบลเกิ้ง อำเภอเมืองมหาสารคาม จังหวัดมหาสารคาม 44000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 16.21304746, longitude: 103.2731427
  },
  {
    id: 'br-st-60944',
    code: 'B944',
    name: 'สาขามุกดาหาร',
    province: 'มุกดาหาร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขามุกดาหาร)",
    address: "311 ถนนชยางกูร ข ตำบลมุกดาหาร อำเภอเมืองมุกดาหาร จังหวัดมุกดาหาร 49000",
    openTime: '07:30',
    closeTime: '18:30',
    phone: '1308',
    storeGroup: 'TWD', latitude: 16.58233517, longitude: 104.7183399
  },
  {
    id: 'br-st-60945',
    code: 'B945',
    name: 'สาขาตรัง',
    province: 'ตรัง',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาตรัง)",
    address: "7/4 หมู่ที่ 7 ตำบลบ้านโพธิ์ อำเภอเมืองตรัง จังหวัดตรัง 92000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 7.56918658, longitude: 99.64431159
  },
  {
    id: 'br-st-60946',
    code: 'B946',
    name: 'สาขาตาก',
    province: 'ตาก',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาตาก)",
    address: "234 หมู่ืัที่ 1 ตำบลแม่ท้อ อำเภอเมืองตาก จังหวัดตาก 63000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 16.84977128, longitude: 99.1114057
  },
  {
    id: 'br-st-60947',
    code: 'B947',
    name: 'สาขาอุดรธานี',
    province: 'อุดรธานี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาอุดรธานี)",
    address: "608 หมู่ืัที่ 4 ตำบลหนองขอนกว้าง อำเภอเมืองอุดรธานี จังหวัดอุดรธานี 41000",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 17.37507318, longitude: 102.8273245
  },
  {
    id: 'br-st-60949',
    code: 'B949',
    name: 'สาขาเชียงใหม่ แอร์พอร์ต',
    province: 'เชียงใหม่',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาเชียงใหม่ แอร์พอร์ต)",
    address: "201 หมู่ที่ 7 ตำบลสุเทพ อำเภอเมืองเชียงใหม่  จังหวัดเชียงใหม่ 50200",
    openTime: '10:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 18.7671189, longitude: 98.9714599
  },
  {
    id: 'br-st-60950',
    code: 'B950',
    name: 'สาขามิตรภาพ ขอนแก่น',
    province: 'ขอนแก่น',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขามิตรภาพ ขอนแก่น)",
    address: "290/2 หมู่ที่ 17 ตำบลในเมือง อำเภอเมืองขอนแก่น จังหวัดขอนแก่น 40000",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 16.4249246, longitude: 102.8214637
  },
  {
    id: 'br-st-60951',
    code: 'B951',
    name: 'สาขาหนองบัวลำภู',
    province: 'หนองบัวลำภู',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาหนองบัวลำภู)",
    address: "310 หมู่ที่ 5 ตำบลหนองภัยศูนย์ อำเภอเมืองหนองบัวลำภู  จังหวัดหนองบัวลำภู 39000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 17.22810419, longitude: 102.4098893
  },
  {
    id: 'br-st-60952',
    code: 'B952',
    name: 'สาขาสระบุรี',
    province: 'สระบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาสระบุรี)",
    address: "88/9 หมู่ที่ 8  ตำบลตลิ่งชัน อำเภอเมืองสระบุรี จังหวัดสระบุรี 18000",
    openTime: '07:30',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.54347322, longitude: 100.9509166
  },
  {
    id: 'br-st-60953',
    code: 'B953',
    name: 'สาขาปทุมธานี',
    province: 'ปทุมธานี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาปทุมธานี)",
    address: "99/10 หมู่ที่ 5 ตำบลบางเดื่อ  อำเภอเมืองปทุมธานี จังหวัดปทุมธานี 12000",
    openTime: '07:00',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.98245107, longitude: 100.5150882
  },
  {
    id: 'br-st-60954',
    code: 'B954',
    name: 'สาขาพัทยาใต้',
    province: 'ชลบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาพัทยาใต้)",
    address: "80/3 หมู่ที่ 12 ตำบลหนองปรือ อำเภอบางละมุง จังหวัดชลบุรี 20150",
    openTime: '07.30',
    closeTime: '20.00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 12.88711403, longitude: 100.8970705
  },
  {
    id: 'br-st-60955',
    code: 'B955',
    name: 'สาขาภูเก็ต ถลาง',
    province: 'ภูเก็ต',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาภูเก็ต ถลาง)",
    address: "46/13 หมู่ที่ 5 ตำบลศรีสุนทร อำเภอถลาง จังหวัดภูเก็ต 83110",
    openTime: '07:30',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 7.98650039, longitude: 98.35759569
  },
  {
    id: 'br-st-60956',
    code: 'B956',
    name: 'สาขาชลบุรี',
    province: 'ชลบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาชลบุรี)",
    address: "413/81 หมู่ที่ 5 ตำบลบ้านสวน อำเภอเมืองชลบุรี จังหวัดชลบุรี 20000",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.35654264, longitude: 100.9989413
  },
  {
    id: 'br-st-60958',
    code: 'B958',
    name: 'สาขาเชียงราย',
    province: 'เชียงราย',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาเชียงราย)",
    address: "99/20 หมู่ 13 ตำบลสันทราย อำเภอเมืองเชียงราย จังหวัดเชียงราย 57000",
    openTime: '07.30',
    closeTime: '20.00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 19.87282954, longitude: 99.82967883
  },
  {
    id: 'br-st-60959',
    code: 'B959',
    name: 'สาขาบางพลี',
    province: 'สมุทรปราการ',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาบางพลี)",
    address: "111/15 หมู่ที่ 9 ตำบลบางปลา อำเภอบางพลี จังหวัดสมุทรปราการ 10540",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.59324512, longitude: 100.7642844
  },
  {
    id: 'br-st-60960',
    code: 'B960',
    name: 'สาขานวมินทร์',
    province: 'กรุงเทพมหานคร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขานวมินทร์)",
    address: "345,345/1 ถนนนวมินทร์ แขวงนวลจันทร์ เขตบึงกุ่ม จังหวัดกรุงเทพมหานคร 10240",
    openTime: '06:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.82404558, longitude: 100.6556652
  },
  {
    id: 'br-st-60961',
    code: 'B961',
    name: 'สาขาศรีราชา',
    province: 'ชลบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาศรีราชา)",
    address: "92/10 หมู่ที่ 10 ตำบลหนองขาม อำเภอศรีราชา จังหวัดชลบุรี 20230",
    openTime: '07:00',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.14188579, longitude: 100.9849817
  },
  {
    id: 'br-st-60962',
    code: 'B962',
    name: 'สาขาแจ้งวัฒนะ',
    province: 'นนทบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาแจ้งวัฒนะ)",
    address: "78 หมู่ที่ 4  ตำบลบางตลาด อำเภอปากเกร็ด จังหวัดนนทบุรี 11120",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.89935168, longitude: 100.5418065
  },
  {
    id: 'br-st-60963',
    code: 'B963',
    name: 'สาขารังสิต 1',
    province: 'ปทุมธานี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขารังสิต 1)",
    address: "13/214 หมู่ที่ 2  ตำบลคลองหนึ่ง อำเภอคลองหลวง จังหวัดปทุมธานี 12120",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.01633465, longitude: 100.6131715
  },
  {
    id: 'br-st-60964',
    code: 'B964',
    name: 'สาขาพระราม 2',
    province: 'กรุงเทพมหานคร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาไทวัสดุ พระราม 2)",
    address: "268/2  ถนนพระรามที่ 2 แขวงแสมดำ  เขตบางขุนเทียน จังหวัดกรุงเทพมหานคร 10150",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.65293721, longitude: 100.4233784
  },
  {
    id: 'br-st-60966',
    code: 'B966',
    name: 'สาขาชัยพฤกษ์',
    province: 'นนทบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาชัยพฤกษ์)",
    address: "46/21 หมู่ที่ 5 ตำบลบางพลับ อำเภอปากเกร็ด จังหวัดนนทบุรี 11120",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'HBY', latitude: 13.93466556, longitude: 100.4547132
  },
  {
    id: 'br-st-60968',
    code: 'B968',
    name: 'สาขาลำลูกกา',
    province: 'ปทุมธานี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาลำลูกกา)",
    address: "67  หมู่ที่ 11  ตำบลลำลูกกา  อำเภอลำลูกกา จังหวัดปทุมธานี 12150",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.93713118, longitude: 100.7538698
  },
  {
    id: 'br-st-60969',
    code: 'B969',
    name: 'สาขาอ้อมน้อย',
    province: 'สมุทรสาคร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาอ้อมน้อย)",
    address: "200/101 หมู่ที่ 6 ตำบลอ้อมน้อย อำเภอกระทุ่มแบน จังหวัดสมุทรสาคร 74130",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.70581529, longitude: 100.3015519
  },
  {
    id: 'br-st-60970',
    code: 'B970',
    name: 'สาขานครราชสีมา',
    province: 'นครราชสีมา',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขานครราชสีมา)",
    address: "475 หมู่1 ตำบลปรุใหญ่ อำเภอเมืองนครราชสีมา จังหวัดนครราชสีมา 30000",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.9896898, longitude: 102.0513416
  },
  {
    id: 'br-st-60971',
    code: 'B971',
    name: 'สาขานครปฐม',
    province: 'นครปฐม',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขานครปฐม)",
    address: "200 หมู่9 ตำบลลำพยา  อำเภอเมืองนครปฐม  จังหวัดนครปฐม 73000",
    openTime: '08:00',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.80284509, longitude: 100.0221746
  },
  {
    id: 'br-st-60972',
    code: 'B972',
    name: 'สาขาศรีมหาโพธิ',
    province: 'ปราจีนบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาศรีมหาโพธิ)",
    address: "898 หมู่ 7 ตำบลท่าตูม อำเภอศรีมหาโพธิ จังหวัดปราจีนบุรี 25140",
    openTime: '07:00',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.89253452, longitude: 101.5761489
  },
  {
    id: 'br-st-60973',
    code: 'B973',
    name: 'สาขาบ้านฉาง',
    province: 'ระยอง',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาบ้านฉาง)",
    address: "55/4 หมู่ 1 ตำบลบ้านฉาง อำเภอบ้านฉาง จังหวัดระยอง 21130",
    openTime: '08:30',
    closeTime: '19:30',
    phone: '1308',
    storeGroup: 'TWD', latitude: 12.73426994, longitude: 101.0771056
  },
  {
    id: 'br-st-60974',
    code: 'B974',
    name: 'สาขาหนองจอก',
    province: 'กรุงเทพมหานคร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาหนองจอก)",
    address: "97 ถนน เลียบวารี เขต หนองจอก จังหวัดกรุงเทพมหานคร 10530",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.855205, longitude: 100.85606
  },
  {
    id: 'br-st-60975',
    code: 'B975',
    name: 'สาขาปากช่อง',
    province: 'นครราชสีมา',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาปากช่อง )",
    address: "7 หมู่ 11 ตำบลหนองน้ำแดง อำเภอปากช่อง จังหวัดนครราชสีมา 30130",
    openTime: '08:00',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.65270667, longitude: 101.4049422
  },
  {
    id: 'br-st-60976',
    code: 'B976',
    name: 'สาขาเพชรบุรี',
    province: 'เพชรบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาเพชรบุรี)",
    address: "120 หมู่9 ตำบลท่าเสน  อำเภอบ้านลาด  จังหวัดเพชรบุรี 76150",
    openTime: '08:00',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.05430615, longitude: 99.94517157
  },
  {
    id: 'br-st-60978',
    code: 'B978',
    name: 'สาขานครศรีธรรมราช',
    province: 'นครศรีธรรมราช',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขานครศรีธรรมราช)",
    address: "162 หมู่ 18 ตำบลท่าเรือ อำเภอเมือง จังหวัดนครศรีธรรมราช 80000",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 8.39205221, longitude: 99.99154355
  },
  {
    id: 'br-st-60979',
    code: 'B979',
    name: 'สาขาสุขสวัสดิ์',
    province: 'สมุทรปราการ',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สุขสวัสดิ์)",
    address: "119/201 ม.14 ต.บางพึ่ง อ.พระประแดง จังหวัดสมุทรปราการ 10130",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.66266679, longitude: 100.5189019
  },
  {
    id: 'br-st-60980',
    code: 'B980',
    name: 'สาขาบ่อวิน',
    province: 'ชลบุรี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (บ่อวิน)",
    address: "274/11 หมู่ 3 ตำตำบลบ่อวิน อำเภอศรีราชา จังหวัดชลบุรี 20230",
    openTime: '08.30',
    closeTime: '19.30',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.03270803, longitude: 101.0974692
  },
  {
    id: 'br-st-60981',
    code: 'B981',
    name: 'สาขาอยุธยา',
    province: 'พระนครศรีอยุธยา',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (อยุธยา)",
    address: "111/3 หมู่ 3 ตำบลคลองสวนพูล อำเภอพระนครศรีอยุธยา จังหวัดพระนครศรีอยุธยา 10300",
    openTime: '07:00',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.34123676, longitude: 100.6117096
  },
  {
    id: 'br-st-60982',
    code: 'B982',
    name: 'สาขาสงขลา',
    province: 'สงขลา',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาสงขลา)",
    address: "125/20 หมู่ 6 ต.น้ำน้อย อ.หาดใหญ่ จังหวัดสงขลา 90110",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 7.12282807, longitude: 100.5521737
  },
  {
    id: 'br-st-60983',
    code: 'B983',
    name: 'สาขาชัยภูมิ',
    province: 'ชัยภูมิ',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (ชัยภูมิ)",
    address: "299/11 หมู่ 6 ตำบลในเมือง อำเภอเมืองชัยภูมิ จังหวัดชัยภูมิ 36000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 15.78771732, longitude: 102.0328356
  },
  {
    id: 'br-st-60984',
    code: 'B984',
    name: 'สาขาน่าน',
    province: 'น่าน',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (น่าน)",
    address: "621 หมู่ 11 ตำบลไชยสถาน อำเภอเมืองน่าน จังหวัดน่าน 55000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 18.78995436, longitude: 100.7366207
  },
  {
    id: 'br-st-60985',
    code: 'B985',
    name: 'สาขาบางบอน',
    province: 'สมุทรสาคร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (บางบอน)",
    address: "89 หมู่ 3 ตำบลบางน้ำจืด อำเภอเมืองสมุทรสาคร จังหวัดสมุทรสาคร 74000",
    openTime: '07:00',
    closeTime: '21:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.6250882, longitude: 100.3551136
  },
  {
    id: 'br-st-60986',
    code: 'B986',
    name: 'สาขาแม่จัน',
    province: 'เชียงราย',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาแม่จัน)",
    address: "516 , 516/1 หมู่ 4  ตำบลแม่จัน อำเภอแม่จัน จังหวัดเชียงราย 57110",
    openTime: '08:00',
    closeTime: '18:30',
    phone: '1308',
    storeGroup: 'TWD', latitude: 20.14319474, longitude: 99.85832748
  },
  {
    id: 'br-st-60987',
    code: 'B987',
    name: 'สาขากำแพงเพชร',
    province: 'กำแพงเพชร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขากำแพงเพชร)",
    address: "139 หมู่ 4 ตำบลท่าขุนราม อำเภอเมืองกำแพงเพชร จังหวัดกำแพงเพชร 62000",
    openTime: '07:30',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 16.456805, longitude: 99.494737
  },
  {
    id: 'br-st-60988',
    code: 'B988',
    name: 'สาขานครราชสีมา (หัวทะเล)',
    province: 'นครราชสีมา',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขานครราชสีมา หัวทะเล)",
    address: "258 หมู่1 ตำบลหนองบัวศาลา อำเภอเมืองนครราชสีมา จังหวัดนครราชสีมา 30000",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 14.945183, longitude: 102.128685
  },
  {
    id: 'br-st-60989',
    code: 'B989',
    name: 'สาขาชัยนาท',
    province: 'ชัยนาท',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาชัยนาท)",
    address: "359 ถนนทางหลวง 340 ตำบลบ้านกล้วย อำเภอเมืองชัยนาท จังหวัดชัยนาท 17000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 15.181546, longitude: 100.136652
  },
  {
    id: 'br-st-60990',
    code: 'B990',
    name: 'สาขาศรีสะเกษ',
    province: 'ศรีสะเกษ',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาศรีสะเกษ)",
    address: "368 หมู่ 6 ตำบลโพนข่า อำเภอเมืองศรีสะเกษ จังหวัดศรีสะเกษ 33000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 15.08153022, longitude: 104.3431375
  },
  {
    id: 'br-st-60991',
    code: 'B991',
    name: 'สาขาเลย',
    province: 'เลย',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาเลย)",
    address: "10/2 ถนนเลย - เชียงคาน ตำบลกุดป่อง อำเภอเมืองเลย จังหวัดเลย 42000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 17.51416484, longitude: 101.726342
  },
  {
    id: 'br-st-60992',
    code: 'B992',
    name: 'สาขายโสธร',
    province: 'ยโสธร',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขายโสธร)",
    address: "458 หมู่ 8 ตำบลตาดทอง อำเภอเมืองยโสธร จังหวัดยโสธร 35000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 15.77573991, longitude: 104.1747636
  },
  {
    id: 'br-st-60993',
    code: 'B993',
    name: 'สาขานครสวรรค์',
    province: 'นครสวรรค์',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขานครสวรรค์)",
    address: "999/99 หมู่ 6  ตำบลหนองกรด อำเภอเมืองนครสวรรค์  จังหวัดนครสวรรค์ 60240",
    openTime: '07:30',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 15.72138, longitude: 100.04857
  },
  {
    id: 'br-st-60994',
    code: 'B994',
    name: 'สาขาอรัญประเทศ',
    province: 'สระแก้ว',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาอรัญประเทศ)",
    address: "2929 หมู่ 5 ตำบลบ้านใหม่หนองไทร อำเภอ อรัญประเทศ จังหวัดสระแก้ว 27120",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.7130812, longitude: 102.4774453
  },
  {
    id: 'br-st-60995',
    code: 'B995',
    name: 'สาขาสระแก้ว',
    province: 'สระแก้ว',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาสระแก้ว)",
    address: "388/88 ถนนสุวรรณศร ตำบลสระแก้ว อำเภอเมืองสระแก้ว จังหวัดสระแก้ว 27000",
    openTime: '08:00',
    closeTime: '20:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 13.80733826, longitude: 102.0823494
  },
  {
    id: 'br-st-60996',
    code: 'B996',
    name: 'สาขาแกลง',
    province: 'ระยอง',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาแกลง)",
    address: "222 หมู่ 12 ตำบลทุ่งควายกิน อำเภอแกลง จังหวัดระยอง 21110",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 12.781291, longitude: 101.694375
  },
  {
    id: 'br-st-60997',
    code: 'B997',
    name: 'สาขาอุทัยธานี',
    province: 'อุทัยธานี',
    status: 'Active',
    fullName: "บริษัท ซีอาร์ซี ไทวัสดุ จำกัด (สาขาอุทัยธานี)",
    address: "723/9,723/10,723/11 ถนนศรีอุทัย ตำบลอุทัยใหม่ อำเภอเมืองอุทัยธานี จังหวัดอุทัยธานี 61000",
    openTime: '08:00',
    closeTime: '19:00',
    phone: '1308',
    storeGroup: 'TWD', latitude: 15.39462554, longitude: 100.0262823
  },
  {
    id: 'br-st-60003',
    code: 'B3',
    name: 'สาขาEVENT HO3',
    province: 'สมุทรปราการ',
    status: 'Active',
    fullName: "CRC Thai Watsadu Limited EXPO HO3",
    address: "88/88 หมู่ที่ 13 ตำบลบางแก้ว อำเภอบางพลี จังหวัดสมุทรปราการ 10540",
    openTime: '10.00',
    closeTime: '21.00',
    phone: '1308',
    storeGroup: 'HO', latitude: 13.652367, longitude: 100.67665
  },
  {
    id: 'br-st-60802',
    code: 'B802',
    name: 'สาขาHO1 Event',
    province: 'สมุทรปราการ',
    status: 'Active',
    fullName: "CRC Thai Watsadu Limited (HO1 Event)",
    address: "88/88 หมู่ที่ 13 ตำบลบางแก้ว อำเภอบางพลี จังหวัดสมุทรปราการ 10540",
    openTime: '10.00',
    closeTime: '21.00',
    phone: '21033333',
    storeGroup: 'HO', latitude: 18.7671189, longitude: 98.9714599
  },
  {
    id: 'br-st-60813',
    code: 'B813',
    name: 'สาขาสำนักงานใหญ่',
    province: 'สมุทรปราการ',
    status: 'Active',
    fullName: "CRC Thai Watsadu Limited (Head Office)",
    address: "88/88 หมู่ที่ 13 ตำบลบางแก้ว อำเภอบางพลี จังหวัดสมุทรปราการ 10540",
    openTime: '07.00',
    closeTime: '21.00',
    phone: '21033333',
    storeGroup: 'TWD', latitude: 13.652367, longitude: 100.67665
  },
  {
    id: 'br-st-60001',
    code: 'B881',
    name: 'สาขาHO-Expo',
    province: 'สมุทรปราการ',
    status: 'Active',
    fullName: "CRC Thai Watsadu Limited (Head office Branch)",
    address: "88/88 หมู่ที่ 13 ตำบลบางแก้ว อำเภอบางพลี จังหวัดสมุทรปราการ 10540",
    openTime: '10.00',
    closeTime: '21.00',
    phone: '1308',
    storeGroup: 'HO', latitude: 13.652367, longitude: 100.67665
  }
];

export const INITIAL_ZONES: Zone[] = [
  {
    "id": "zone-bkk-c1",
    "code": "Z01-C1",
    "name": "[BKK] กรุงเทพฯ ชั้นใน (เมืองเก่า / พญาไท - ราชเทวี)",
    "description": "ครอบคลุมเขตพระนคร, ดุสิต, ป้อมปราบศัตรูพ่าย, สัมพันธวงศ์, พญาไท, ราชเทวี",
    "coverageZipcodes": ["10100", "10200", "10300", "10400"]
  },
  {
    "id": "zone-bkk-c2",
    "code": "Z01-C2",
    "name": "[BKK] กรุงเทพฯ ชั้นใน (ศูนย์กลางธุรกิจ / สาทร - สีลม - บางรัก - พระราม 3)",
    "description": "ครอบคลุมเขตปทุมวัน, บางรัก, สาทร, ยานนาวา, บางคอแหลม",
    "coverageZipcodes": ["10120", "10330", "10500"]
  },
  {
    "id": "zone-bkk-c3",
    "code": "Z01-C3",
    "name": "[BKK] กรุงเทพฯ ชั้นใน (สุขุมวิท / ดินแดง - ห้วยขวาง - คลองเตย)",
    "description": "ครอบคลุมเขตดินแดง, ห้วยขวาง, วัฒนา, คลองเตย",
    "coverageZipcodes": ["10110", "10310"]
  },
  {
    "id": "zone-bkk-n1",
    "code": "Z01-N1",
    "name": "[BKK] กรุงเทพฯ เหนือตอนล่าง (จตุจักร - บางซื่อ - ลาดพร้าว)",
    "description": "ครอบคลุมเขตจตุจักร, บางซื่อ, ลาดพร้าว",
    "coverageZipcodes": ["10800", "10900", "10230"]
  },
  {
    "id": "zone-bkk-n2",
    "code": "Z01-N2",
    "name": "[BKK] กรุงเทพฯ เหนือตอนบน (หลักสี่ - ดอนเมือง - สายไหม - บางเขน)",
    "description": "ครอบคลุมเขตหลักสี่, ดอนเมือง, สายไหม, บางเขน",
    "coverageZipcodes": ["10210", "10220"]
  },
  {
    "id": "zone-bkk-e1",
    "code": "Z01-E1",
    "name": "[BKK] กรุงเทพฯ ตะวันออก (บางกะปิ - บึงกุ่ม - สะพานสูง - วังทองหลาง - คันนายาว)",
    "description": "ครอบคลุมเขตบางกะปิ, บึงกุ่ม, สะพานสูง, วังทองหลาง, คันนายาว",
    "coverageZipcodes": ["10240", "10310"]
  },
  {
    "id": "zone-bkk-e2",
    "code": "Z01-E2",
    "name": "[BKK] กรุงเทพฯ ตะวันออกนอก (มีนบุรี - ลาดกระบัง - หนองจอก - คลองสามวา)",
    "description": "ครอบคลุมเขตคลองสามวา, หนองจอก, มีนบุรี, ลาดกระบัง",
    "coverageZipcodes": ["10510", "10520"]
  },
  {
    "id": "zone-bkk-se",
    "code": "Z01-SE",
    "name": "[BKK] กรุงเทพฯ ตะวันออกใต้ (ประเวศ - สวนหลวง - บางนา)",
    "description": "ครอบคลุมเขตประเวศ, สวนหลวง, บางนา",
    "coverageZipcodes": ["10250", "10260"]
  },
  {
    "id": "zone-bkk-w1",
    "code": "Z01-W1",
    "name": "[BKK] กรุงเทพฯ ฝั่งธนบุรีเหนือ (ธนบุรี - คลองสาน - บางกอกน้อย - บางพลัด - ตลิ่งชัน - ทวีวัฒนา)",
    "description": "ครอบคลุมเขตธนบุรี, คลองสาน, บางกอกใหญ่, บางกอกน้อย, บางพลัด, ตลิ่งชัน, ทวีวัฒนา",
    "coverageZipcodes": ["10170", "10600", "10700"]
  },
  {
    "id": "zone-bkk-w2",
    "code": "Z01-W2",
    "name": "[BKK] กรุงเทพฯ ฝั่งธนบุรีใต้ (ภาษีเจริญ - บางแค - หนองแขม - ราษฎร์บูรณะ - ทุ่งครุ - จอมทอง - บางขุนเทียน - บางบอน)",
    "description": "ครอบคลุมเขตภาษีเจริญ, บางแค, หนองแขม, ราษฎร์บูรณะ, ทุ่งครุ, จอมทอง, บางขุนเทียน, บางบอน",
    "coverageZipcodes": ["10140", "10150", "10160"]
  },
  {
    "id": "zone-2",
    "code": "Z02",
    "name": "[BKK] นนทบุรี",
    "description": "พื้นที่ให้บริการภูมิภาค BKK (นนทบุรี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-3",
    "code": "Z03",
    "name": "[BKK] ปทุมธานี",
    "description": "พื้นที่ให้บริการภูมิภาค BKK (ปทุมธานี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-4",
    "code": "Z04",
    "name": "[BKK] สมุทรปราการ",
    "description": "พื้นที่ให้บริการภูมิภาค BKK (สมุทรปราการ)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-5",
    "code": "Z05",
    "name": "[CT] กำแพงเพชร",
    "description": "พื้นที่ให้บริการภูมิภาค CT (กำแพงเพชร)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-6",
    "code": "Z06",
    "name": "[CT] ชัยนาท",
    "description": "พื้นที่ให้บริการภูมิภาค CT (ชัยนาท)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-7",
    "code": "Z07",
    "name": "[CT] นครนายก",
    "description": "พื้นที่ให้บริการภูมิภาค CT (นครนายก)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-8",
    "code": "Z08",
    "name": "[CT] นครปฐม",
    "description": "พื้นที่ให้บริการภูมิภาค CT (นครปฐม)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-9",
    "code": "Z09",
    "name": "[CT] นครสวรรค์",
    "description": "พื้นที่ให้บริการภูมิภาค CT (นครสวรรค์)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-10",
    "code": "Z10",
    "name": "[CT] อยุธยา",
    "description": "พื้นที่ให้บริการภูมิภาค CT (อยุธยา)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-11",
    "code": "Z11",
    "name": "[CT] พระนครศรีอยุธยา",
    "description": "พื้นที่ให้บริการภูมิภาค CT (พระนครศรีอยุธยา)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-12",
    "code": "Z12",
    "name": "[CT] พิจิตร",
    "description": "พื้นที่ให้บริการภูมิภาค CT (พิจิตร)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-13",
    "code": "Z13",
    "name": "[CT] พิษณุโลก",
    "description": "พื้นที่ให้บริการภูมิภาค CT (พิษณุโลก)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-14",
    "code": "Z14",
    "name": "[CT] เพชรบูรณ์",
    "description": "พื้นที่ให้บริการภูมิภาค CT (เพชรบูรณ์)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-15",
    "code": "Z15",
    "name": "[CT] ลพบุรี",
    "description": "พื้นที่ให้บริการภูมิภาค CT (ลพบุรี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-16",
    "code": "Z16",
    "name": "[CT] สมุทรสงคราม",
    "description": "พื้นที่ให้บริการภูมิภาค CT (สมุทรสงคราม)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-17",
    "code": "Z17",
    "name": "[CT] สมุทรสาคร",
    "description": "พื้นที่ให้บริการภูมิภาค CT (สมุทรสาคร)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-18",
    "code": "Z18",
    "name": "[CT] สระบุรี",
    "description": "พื้นที่ให้บริการภูมิภาค CT (สระบุรี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-19",
    "code": "Z19",
    "name": "[CT] สิงห์บุรี",
    "description": "พื้นที่ให้บริการภูมิภาค CT (สิงห์บุรี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-20",
    "code": "Z20",
    "name": "[CT] สุโขทัย",
    "description": "พื้นที่ให้บริการภูมิภาค CT (สุโขทัย)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-21",
    "code": "Z21",
    "name": "[CT] สุพรรณบุรี",
    "description": "พื้นที่ให้บริการภูมิภาค CT (สุพรรณบุรี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-22",
    "code": "Z22",
    "name": "[CT] อ่างทอง",
    "description": "พื้นที่ให้บริการภูมิภาค CT (อ่างทอง)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-23",
    "code": "Z23",
    "name": "[CT] อุทัยธานี",
    "description": "พื้นที่ให้บริการภูมิภาค CT (อุทัยธานี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-24",
    "code": "Z24",
    "name": "[ET] จันทบุรี",
    "description": "พื้นที่ให้บริการภูมิภาค ET (จันทบุรี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-25",
    "code": "Z25",
    "name": "[ET] ฉะเชิงเทรา",
    "description": "พื้นที่ให้บริการภูมิภาค ET (ฉะเชิงเทรา)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-26",
    "code": "Z26",
    "name": "[ET] ชลบุรี",
    "description": "พื้นที่ให้บริการภูมิภาค ET (ชลบุรี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-27",
    "code": "Z27",
    "name": "[ET] ตราด",
    "description": "พื้นที่ให้บริการภูมิภาค ET (ตราด)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-28",
    "code": "Z28",
    "name": "[ET] ปราจีนบุรี",
    "description": "พื้นที่ให้บริการภูมิภาค ET (ปราจีนบุรี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-29",
    "code": "Z29",
    "name": "[ET] ระยอง",
    "description": "พื้นที่ให้บริการภูมิภาค ET (ระยอง)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-30",
    "code": "Z30",
    "name": "[ET] สระแก้ว",
    "description": "พื้นที่ให้บริการภูมิภาค ET (สระแก้ว)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-31",
    "code": "Z31",
    "name": "[NE] กาฬสินธุ์",
    "description": "พื้นที่ให้บริการภูมิภาค NE (กาฬสินธุ์)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-32",
    "code": "Z32",
    "name": "[NE] ขอนแก่น",
    "description": "พื้นที่ให้บริการภูมิภาค NE (ขอนแก่น)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-33",
    "code": "Z33",
    "name": "[NE] ชัยภูมิ",
    "description": "พื้นที่ให้บริการภูมิภาค NE (ชัยภูมิ)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-34",
    "code": "Z34",
    "name": "[NE] นครพนม",
    "description": "พื้นที่ให้บริการภูมิภาค NE (นครพนม)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-35",
    "code": "Z35",
    "name": "[NE] นครราชสีมา",
    "description": "พื้นที่ให้บริการภูมิภาค NE (นครราชสีมา)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-36",
    "code": "Z36",
    "name": "[NE] บึงกาฬ",
    "description": "พื้นที่ให้บริการภูมิภาค NE (บึงกาฬ)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-37",
    "code": "Z37",
    "name": "[NE] บุรีรัมย์",
    "description": "พื้นที่ให้บริการภูมิภาค NE (บุรีรัมย์)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-38",
    "code": "Z38",
    "name": "[NE] มหาสารคาม",
    "description": "พื้นที่ให้บริการภูมิภาค NE (มหาสารคาม)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-39",
    "code": "Z39",
    "name": "[NE] มุกดาหาร",
    "description": "พื้นที่ให้บริการภูมิภาค NE (มุกดาหาร)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-40",
    "code": "Z40",
    "name": "[NE] ยโสธร",
    "description": "พื้นที่ให้บริการภูมิภาค NE (ยโสธร)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-41",
    "code": "Z41",
    "name": "[NE] ร้อยเอ็ด",
    "description": "พื้นที่ให้บริการภูมิภาค NE (ร้อยเอ็ด)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-42",
    "code": "Z42",
    "name": "[NE] เลย",
    "description": "พื้นที่ให้บริการภูมิภาค NE (เลย)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-43",
    "code": "Z43",
    "name": "[NE] ศรีสะเกษ",
    "description": "พื้นที่ให้บริการภูมิภาค NE (ศรีสะเกษ)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-44",
    "code": "Z44",
    "name": "[NE] สกลนคร",
    "description": "พื้นที่ให้บริการภูมิภาค NE (สกลนคร)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-45",
    "code": "Z45",
    "name": "[NE] สุรินทร์",
    "description": "พื้นที่ให้บริการภูมิภาค NE (สุรินทร์)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-46",
    "code": "Z46",
    "name": "[NE] หนองคาย",
    "description": "พื้นที่ให้บริการภูมิภาค NE (หนองคาย)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-47",
    "code": "Z47",
    "name": "[NE] หนองบัวลำภู",
    "description": "พื้นที่ให้บริการภูมิภาค NE (หนองบัวลำภู)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-48",
    "code": "Z48",
    "name": "[NE] อำนาจเจริญ",
    "description": "พื้นที่ให้บริการภูมิภาค NE (อำนาจเจริญ)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-49",
    "code": "Z49",
    "name": "[NE] อุดรธานี",
    "description": "พื้นที่ให้บริการภูมิภาค NE (อุดรธานี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-50",
    "code": "Z50",
    "name": "[NE] อุบลราชธานี",
    "description": "พื้นที่ให้บริการภูมิภาค NE (อุบลราชธานี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-51",
    "code": "Z51",
    "name": "[NT] เชียงราย",
    "description": "พื้นที่ให้บริการภูมิภาค NT (เชียงราย)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-52",
    "code": "Z52",
    "name": "[NT] เชียงใหม่",
    "description": "พื้นที่ให้บริการภูมิภาค NT (เชียงใหม่)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-53",
    "code": "Z53",
    "name": "[NT] น่าน",
    "description": "พื้นที่ให้บริการภูมิภาค NT (น่าน)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-54",
    "code": "Z54",
    "name": "[NT] พะเยา",
    "description": "พื้นที่ให้บริการภูมิภาค NT (พะเยา)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-55",
    "code": "Z55",
    "name": "[NT] แพร่",
    "description": "พื้นที่ให้บริการภูมิภาค NT (แพร่)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-56",
    "code": "Z56",
    "name": "[NT] แม่ฮ่องสอน",
    "description": "พื้นที่ให้บริการภูมิภาค NT (แม่ฮ่องสอน)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-57",
    "code": "Z57",
    "name": "[NT] ลำปาง",
    "description": "พื้นที่ให้บริการภูมิภาค NT (ลำปาง)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-58",
    "code": "Z58",
    "name": "[NT] ลำพูน",
    "description": "พื้นที่ให้บริการภูมิภาค NT (ลำพูน)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-59",
    "code": "Z59",
    "name": "[NT] อุตรดิตถ์",
    "description": "พื้นที่ให้บริการภูมิภาค NT (อุตรดิตถ์)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-60",
    "code": "Z60",
    "name": "[ST] กระบี่",
    "description": "พื้นที่ให้บริการภูมิภาค ST (กระบี่)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-61",
    "code": "Z61",
    "name": "[ST] ชุมพร",
    "description": "พื้นที่ให้บริการภูมิภาค ST (ชุมพร)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-62",
    "code": "Z62",
    "name": "[ST] ตรัง",
    "description": "พื้นที่ให้บริการภูมิภาค ST (ตรัง)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-63",
    "code": "Z63",
    "name": "[ST] นครศรีธรรมราช",
    "description": "พื้นที่ให้บริการภูมิภาค ST (นครศรีธรรมราช)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-64",
    "code": "Z64",
    "name": "[ST] นราธิวาส",
    "description": "พื้นที่ให้บริการภูมิภาค ST (นราธิวาส)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-65",
    "code": "Z65",
    "name": "[ST] ปัตตานี",
    "description": "พื้นที่ให้บริการภูมิภาค ST (ปัตตานี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-66",
    "code": "Z66",
    "name": "[ST] พังงา",
    "description": "พื้นที่ให้บริการภูมิภาค ST (พังงา)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-67",
    "code": "Z67",
    "name": "[ST] พัทลุง",
    "description": "พื้นที่ให้บริการภูมิภาค ST (พัทลุง)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-68",
    "code": "Z68",
    "name": "[ST] ภูเก็ต",
    "description": "พื้นที่ให้บริการภูมิภาค ST (ภูเก็ต)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-69",
    "code": "Z69",
    "name": "[ST] ยะลา",
    "description": "พื้นที่ให้บริการภูมิภาค ST (ยะลา)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-70",
    "code": "Z70",
    "name": "[ST] ระนอง",
    "description": "พื้นที่ให้บริการภูมิภาค ST (ระนอง)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-71",
    "code": "Z71",
    "name": "[ST] สงขลา",
    "description": "พื้นที่ให้บริการภูมิภาค ST (สงขลา)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-72",
    "code": "Z72",
    "name": "[ST] สตูล",
    "description": "พื้นที่ให้บริการภูมิภาค ST (สตูล)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-73",
    "code": "Z73",
    "name": "[ST] สุราษฎร์ธานี",
    "description": "พื้นที่ให้บริการภูมิภาค ST (สุราษฎร์ธานี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-74",
    "code": "Z74",
    "name": "[WE] กาญจนบุรี",
    "description": "พื้นที่ให้บริการภูมิภาค WE (กาญจนบุรี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-75",
    "code": "Z75",
    "name": "[WE] ตาก",
    "description": "พื้นที่ให้บริการภูมิภาค WE (ตาก)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-76",
    "code": "Z76",
    "name": "[WE] ประจวบคีรีขันธ์",
    "description": "พื้นที่ให้บริการภูมิภาค WE (ประจวบคีรีขันธ์)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-77",
    "code": "Z77",
    "name": "[WE] เพชรบุรี",
    "description": "พื้นที่ให้บริการภูมิภาค WE (เพชรบุรี)",
    "coverageZipcodes": []
  },
  {
    "id": "zone-78",
    "code": "Z78",
    "name": "[WE] ราชบุรี",
    "description": "พื้นที่ให้บริการภูมิภาค WE (ราชบุรี)",
    "coverageZipcodes": []
  }
];

export const INITIAL_SKILLS: Skill[] = [
  {
    "id": "sk-1",
    "code": "SK-01",
    "category": "CE",
    "name": "ติดตั้งแอร์ติดผนัง",
    "description": "ความเชี่ยวชาญกลุ่มงาน CE: ติดตั้งแอร์ติดผนัง",
    "certificationRequired": true
  },
  {
    "id": "sk-2",
    "code": "SK-02",
    "category": "CE",
    "name": "ติดตั้งแอร์แขวน",
    "description": "ความเชี่ยวชาญกลุ่มงาน CE: ติดตั้งแอร์แขวน",
    "certificationRequired": true
  },
  {
    "id": "sk-3",
    "code": "SK-03",
    "category": "CE",
    "name": "ติดตั้งแอร์สี่ทิศทาง",
    "description": "ความเชี่ยวชาญกลุ่มงาน CE: ติดตั้งแอร์สี่ทิศทาง",
    "certificationRequired": true
  },
  {
    "id": "sk-4",
    "code": "SK-04",
    "category": "CE",
    "name": "ติดตั้งเครื่องทำน้ำอุ่น/น้ำร้อน",
    "description": "ความเชี่ยวชาญกลุ่มงาน CE: ติดตั้งเครื่องทำน้ำอุ่น/น้ำร้อน",
    "certificationRequired": true
  },
  {
    "id": "sk-5",
    "code": "SK-05",
    "category": "CE",
    "name": "ติดตั้งเครื่องทำน้ำร้อนแบบหม้อต้ม",
    "description": "ความเชี่ยวชาญกลุ่มงาน CE: ติดตั้งเครื่องทำน้ำร้อนแบบหม้อต้ม",
    "certificationRequired": true
  },
  {
    "id": "sk-6",
    "code": "SK-06",
    "category": "CEC",
    "name": "งานล้างเครื่องซักผ้าฝาบน แบบถอดซัก",
    "description": "ความเชี่ยวชาญกลุ่มงาน CEC: งานล้างเครื่องซักผ้าฝาบน แบบถอดซัก",
    "certificationRequired": false
  },
  {
    "id": "sk-7",
    "code": "SK-07",
    "category": "CEC",
    "name": "งานล้างแอร์",
    "description": "ความเชี่ยวชาญกลุ่มงาน CEC: งานล้างแอร์",
    "certificationRequired": false
  },
  {
    "id": "sk-8",
    "code": "SK-08",
    "category": "CEC",
    "name": "ติดตั้งเครื่องกรองน้ำใช้",
    "description": "ความเชี่ยวชาญกลุ่มงาน CEC: ติดตั้งเครื่องกรองน้ำใช้",
    "certificationRequired": false
  },
  {
    "id": "sk-9",
    "code": "SK-09",
    "category": "CEC",
    "name": "ติดตั้งเครื่องกรองน้ำ",
    "description": "ความเชี่ยวชาญกลุ่มงาน CEC: ติดตั้งเครื่องกรองน้ำ",
    "certificationRequired": false
  },
  {
    "id": "sk-10",
    "code": "SK-10",
    "category": "CEC",
    "name": "ติดตั้งเครื่องกรองน้ำ ระบบไฟฟ้า",
    "description": "ความเชี่ยวชาญกลุ่มงาน CEC: ติดตั้งเครื่องกรองน้ำ ระบบไฟฟ้า",
    "certificationRequired": false
  },
  {
    "id": "sk-11",
    "code": "SK-11",
    "category": "CEC",
    "name": "ติดตั้งปั๊มแท็งค์",
    "description": "ความเชี่ยวชาญกลุ่มงาน CEC: ติดตั้งปั๊มแท็งค์",
    "certificationRequired": false
  },
  {
    "id": "sk-12",
    "code": "SK-12",
    "category": "SOLAR",
    "name": "ติดตั้งโซล่าเซล / รวมสินค้า / ไม่รวมสินค้า",
    "description": "ความเชี่ยวชาญกลุ่มงาน SOLAR: ติดตั้งโซล่าเซล / รวมสินค้า / ไม่รวมสินค้า",
    "certificationRequired": true
  },
  {
    "id": "sk-13",
    "code": "SK-13",
    "category": "SOLAR",
    "name": "ติดตั้งโซล่าปั้ม",
    "description": "ความเชี่ยวชาญกลุ่มงาน SOLAR: ติดตั้งโซล่าปั้ม",
    "certificationRequired": true
  },
  {
    "id": "sk-14",
    "code": "SK-14",
    "category": "SOLAR",
    "name": "ติดตั้งเครื่องดูดควัน หมุนเวียน",
    "description": "ความเชี่ยวชาญกลุ่มงาน SOLAR: ติดตั้งเครื่องดูดควัน หมุนเวียน",
    "certificationRequired": true
  },
  {
    "id": "sk-15",
    "code": "SK-15",
    "category": "SOLAR",
    "name": "ติดตั้งเครื่องดูดควัน ต่อท่อนอกอาคาร",
    "description": "ความเชี่ยวชาญกลุ่มงาน SOLAR: ติดตั้งเครื่องดูดควัน ต่อท่อนอกอาคาร",
    "certificationRequired": true
  },
  {
    "id": "sk-16",
    "code": "SK-16",
    "category": "SOLAR",
    "name": "ติดตั้งเตาฝังแก๊ส",
    "description": "ความเชี่ยวชาญกลุ่มงาน SOLAR: ติดตั้งเตาฝังแก๊ส",
    "certificationRequired": true
  },
  {
    "id": "sk-17",
    "code": "SK-17",
    "category": "SOLAR",
    "name": "ติดตั้งเตาอบไฟฟ้า / เตาไฟฟ้า",
    "description": "ความเชี่ยวชาญกลุ่มงาน SOLAR: ติดตั้งเตาอบไฟฟ้า / เตาไฟฟ้า",
    "certificationRequired": true
  },
  {
    "id": "sk-18",
    "code": "SK-18",
    "category": "SOLAR",
    "name": "งานล้างเครื่องดูดควัน",
    "description": "ความเชี่ยวชาญกลุ่มงาน SOLAR: งานล้างเครื่องดูดควัน",
    "certificationRequired": true
  },
  {
    "id": "sk-19",
    "code": "SK-19",
    "category": "Electrical",
    "name": "งานระบบไฟฟ้า / บ้าน / อาคาร",
    "description": "ความเชี่ยวชาญกลุ่มงาน Electrical: งานระบบไฟฟ้า / บ้าน / อาคาร",
    "certificationRequired": true
  },
  {
    "id": "sk-20",
    "code": "SK-20",
    "category": "Electrical",
    "name": "ติดตั้งพัดลมดูดอากาศเจาะปูน/ฝังฝ้า",
    "description": "ความเชี่ยวชาญกลุ่มงาน Electrical: ติดตั้งพัดลมดูดอากาศเจาะปูน/ฝังฝ้า",
    "certificationRequired": true
  },
  {
    "id": "sk-21",
    "code": "SK-21",
    "category": "Electrical",
    "name": "ติดตั้งพัดลมโคมไฟ",
    "description": "ความเชี่ยวชาญกลุ่มงาน Electrical: ติดตั้งพัดลมโคมไฟ",
    "certificationRequired": true
  },
  {
    "id": "sk-22",
    "code": "SK-22",
    "category": "Electrical",
    "name": "ติดตั้งสวิทช์ / ปลั๊ก / พัดลม / โคมไฟ / ดาวน์ไลน์",
    "description": "ความเชี่ยวชาญกลุ่มงาน Electrical: ติดตั้งสวิทช์ / ปลั๊ก / พัดลม / โคมไฟ / ดาวน์ไลน์",
    "certificationRequired": true
  },
  {
    "id": "sk-23",
    "code": "SK-23",
    "category": "Electrical",
    "name": "ติดตั้งไฟหัวเสา / โคมไฟกิ่ง",
    "description": "ความเชี่ยวชาญกลุ่มงาน Electrical: ติดตั้งไฟหัวเสา / โคมไฟกิ่ง",
    "certificationRequired": true
  },
  {
    "id": "sk-24",
    "code": "SK-24",
    "category": "Electrical",
    "name": "ติดตั้งโคมไฟระย้า",
    "description": "ความเชี่ยวชาญกลุ่มงาน Electrical: ติดตั้งโคมไฟระย้า",
    "certificationRequired": true
  },
  {
    "id": "sk-25",
    "code": "SK-25",
    "category": "Electrical",
    "name": "ติดตั้งกล้องวงจรปิด",
    "description": "ความเชี่ยวชาญกลุ่มงาน Electrical: ติดตั้งกล้องวงจรปิด",
    "certificationRequired": true
  },
  {
    "id": "sk-26",
    "code": "SK-26",
    "category": "Electrical",
    "name": "ติดตั้งกุญแจดิจิตอล RIM Lock / Mortise",
    "description": "ความเชี่ยวชาญกลุ่มงาน Electrical: ติดตั้งกุญแจดิจิตอล RIM Lock / Mortise",
    "certificationRequired": true
  },
  {
    "id": "sk-27",
    "code": "SK-27",
    "category": "Certain",
    "name": "ติดตั้งผ้าม่านสั่งตัด",
    "description": "ความเชี่ยวชาญกลุ่มงาน Certain: ติดตั้งผ้าม่านสั่งตัด",
    "certificationRequired": false
  },
  {
    "id": "sk-28",
    "code": "SK-28",
    "category": "Certain",
    "name": "ติดตั้งรางม่าน / ม่านสำเร็จรูป",
    "description": "ความเชี่ยวชาญกลุ่มงาน Certain: ติดตั้งรางม่าน / ม่านสำเร็จรูป",
    "certificationRequired": false
  },
  {
    "id": "sk-29",
    "code": "SK-29",
    "category": "Certain",
    "name": "งานติดวอลเปเปอร์",
    "description": "ความเชี่ยวชาญกลุ่มงาน Certain: งานติดวอลเปเปอร์",
    "certificationRequired": false
  },
  {
    "id": "sk-30",
    "code": "SK-30",
    "category": "Bath",
    "name": "ติดตั้งสุขภัณฑ์",
    "description": "ความเชี่ยวชาญกลุ่มงาน Bath: ติดตั้งสุขภัณฑ์",
    "certificationRequired": false
  },
  {
    "id": "sk-31",
    "code": "SK-31",
    "category": "Bath",
    "name": "ติดตั้งสุขภัณฑ์ ระบบไฟฟ้า",
    "description": "ความเชี่ยวชาญกลุ่มงาน Bath: ติดตั้งสุขภัณฑ์ ระบบไฟฟ้า",
    "certificationRequired": false
  },
  {
    "id": "sk-32",
    "code": "SK-32",
    "category": "Bath",
    "name": "ติดตั้งอุปกรณ์ห้องน้ำ",
    "description": "ความเชี่ยวชาญกลุ่มงาน Bath: ติดตั้งอุปกรณ์ห้องน้ำ",
    "certificationRequired": false
  },
  {
    "id": "sk-33",
    "code": "SK-33",
    "category": "Bath",
    "name": "ติดตั้งฉากกั้นอาบน้ำ",
    "description": "ความเชี่ยวชาญกลุ่มงาน Bath: ติดตั้งฉากกั้นอาบน้ำ",
    "certificationRequired": false
  },
  {
    "id": "sk-34",
    "code": "SK-34",
    "category": "Bath",
    "name": "ติดตั้งฉากกั้นอาบน้ำแบบสั่งตัด",
    "description": "ความเชี่ยวชาญกลุ่มงาน Bath: ติดตั้งฉากกั้นอาบน้ำแบบสั่งตัด",
    "certificationRequired": false
  },
  {
    "id": "sk-35",
    "code": "SK-35",
    "category": "Bath",
    "name": "ติดตั้งโถปัสสาวะ",
    "description": "ความเชี่ยวชาญกลุ่มงาน Bath: ติดตั้งโถปัสสาวะ",
    "certificationRequired": false
  },
  {
    "id": "sk-36",
    "code": "SK-36",
    "category": "Bath",
    "name": "ติดตั้งโถปัสสาวะ อัตโนมัติระบบไฟฟ้า",
    "description": "ความเชี่ยวชาญกลุ่มงาน Bath: ติดตั้งโถปัสสาวะ อัตโนมัติระบบไฟฟ้า",
    "certificationRequired": false
  },
  {
    "id": "sk-37",
    "code": "SK-37",
    "category": "Bath",
    "name": "ติดตั้งอ่างล้างหน้า",
    "description": "ความเชี่ยวชาญกลุ่มงาน Bath: ติดตั้งอ่างล้างหน้า",
    "certificationRequired": false
  },
  {
    "id": "sk-38",
    "code": "SK-38",
    "category": "KC",
    "name": "ประกอบเฟอร์นิเจอร์",
    "description": "ความเชี่ยวชาญกลุ่มงาน KC: ประกอบเฟอร์นิเจอร์",
    "certificationRequired": false
  },
  {
    "id": "sk-39",
    "code": "SK-39",
    "category": "KC",
    "name": "ประกอบชุดครัวสำเร็จรูป",
    "description": "ความเชี่ยวชาญกลุ่มงาน KC: ประกอบชุดครัวสำเร็จรูป",
    "certificationRequired": false
  },
  {
    "id": "sk-40",
    "code": "SK-40",
    "category": "KC",
    "name": "ประกอบชุดครัวสำเร็จรูปเจาะ TOP",
    "description": "ความเชี่ยวชาญกลุ่มงาน KC: ประกอบชุดครัวสำเร็จรูปเจาะ TOP",
    "certificationRequired": false
  },
  {
    "id": "sk-41",
    "code": "SK-41",
    "category": "KC",
    "name": "ติดตั้งอ่างล้างจาน / อ่างซิงค์",
    "description": "ความเชี่ยวชาญกลุ่มงาน KC: ติดตั้งอ่างล้างจาน / อ่างซิงค์",
    "certificationRequired": false
  },
  {
    "id": "sk-42",
    "code": "SK-42",
    "category": "Door",
    "name": "ติดตั้งลูกบิด / ก้านโยก",
    "description": "ความเชี่ยวชาญกลุ่มงาน Door: ติดตั้งลูกบิด / ก้านโยก",
    "certificationRequired": false
  },
  {
    "id": "sk-43",
    "code": "SK-43",
    "category": "Door",
    "name": "ติดตั้งโช๊คอัพ",
    "description": "ความเชี่ยวชาญกลุ่มงาน Door: ติดตั้งโช๊คอัพ",
    "certificationRequired": false
  },
  {
    "id": "sk-44",
    "code": "SK-44",
    "category": "Door",
    "name": "ติดตั้งประตู / หน้าต่าง อลูมิเนียม",
    "description": "ความเชี่ยวชาญกลุ่มงาน Door: ติดตั้งประตู / หน้าต่าง อลูมิเนียม",
    "certificationRequired": false
  },
  {
    "id": "sk-45",
    "code": "SK-45",
    "category": "Door",
    "name": "ติดตั้งหน้าต่างบานกระทุ้ง / บานสวิง / บานเลื่อน",
    "description": "ความเชี่ยวชาญกลุ่มงาน Door: ติดตั้งหน้าต่างบานกระทุ้ง / บานสวิง / บานเลื่อน",
    "certificationRequired": false
  },
  {
    "id": "sk-46",
    "code": "SK-46",
    "category": "Door",
    "name": "ติดตั้งกระเบื้องยาง / SPC",
    "description": "ความเชี่ยวชาญกลุ่มงาน Door: ติดตั้งกระเบื้องยาง / SPC",
    "certificationRequired": false
  },
  {
    "id": "sk-47",
    "code": "SK-47",
    "category": "Door",
    "name": "ติดตั้งกระเบื้อง / ลามิเนต",
    "description": "ความเชี่ยวชาญกลุ่มงาน Door: ติดตั้งกระเบื้อง / ลามิเนต",
    "certificationRequired": false
  },
  {
    "id": "sk-48",
    "code": "SK-48",
    "category": "Constuction",
    "name": "งานโครงสร้าง",
    "description": "ความเชี่ยวชาญกลุ่มงาน Constuction: งานโครงสร้าง",
    "certificationRequired": false
  },
  {
    "id": "sk-49",
    "code": "SK-49",
    "category": "Constuction",
    "name": "งานทาสี / ภายใน / ภายนอก",
    "description": "ความเชี่ยวชาญกลุ่มงาน Constuction: งานทาสี / ภายใน / ภายนอก",
    "certificationRequired": false
  },
  {
    "id": "sk-50",
    "code": "SK-50",
    "category": "Constuction",
    "name": "งานผนัง WPC",
    "description": "ความเชี่ยวชาญกลุ่มงาน Constuction: งานผนัง WPC",
    "certificationRequired": false
  },
  {
    "id": "sk-51",
    "code": "SK-51",
    "category": "Constuction",
    "name": "งานติดตั้งแผ่นผนัง PVC Wall",
    "description": "ความเชี่ยวชาญกลุ่มงาน Constuction: งานติดตั้งแผ่นผนัง PVC Wall",
    "certificationRequired": false
  },
  {
    "id": "sk-52",
    "code": "SK-52",
    "category": "Constuction",
    "name": "งานติดตั้งหลังคาโครงเหล็ก",
    "description": "ความเชี่ยวชาญกลุ่มงาน Constuction: งานติดตั้งหลังคาโครงเหล็ก",
    "certificationRequired": false
  },
  {
    "id": "sk-53",
    "code": "SK-53",
    "category": "Constuction",
    "name": "งาน Renovate ต่อเติม ปรับปรุง",
    "description": "ความเชี่ยวชาญกลุ่มงาน Constuction: งาน Renovate ต่อเติม ปรับปรุง",
    "certificationRequired": false
  },
  {
    "id": "sk-54",
    "code": "SK-54",
    "category": "Constuction",
    "name": "งานเดินท่อประปา",
    "description": "ความเชี่ยวชาญกลุ่มงาน Constuction: งานเดินท่อประปา",
    "certificationRequired": false
  },
  {
    "id": "sk-55",
    "code": "SK-55",
    "category": "Maid",
    "name": "งานล้างถังเก็บน้ำ ขนาดไม่เกิน 200 ลิตร",
    "description": "ความเชี่ยวชาญกลุ่มงาน Maid: งานล้างถังเก็บน้ำ ขนาดไม่เกิน 200 ลิตร",
    "certificationRequired": false
  },
  {
    "id": "sk-56",
    "code": "SK-56",
    "category": "Maid",
    "name": "ติดตั้งหญ้าเทียม",
    "description": "ความเชี่ยวชาญกลุ่มงาน Maid: ติดตั้งหญ้าเทียม",
    "certificationRequired": false
  },
  {
    "id": "sk-57",
    "code": "SK-57",
    "category": "Maid",
    "name": "จัดสวน / ตัดแต่งกิ่ง / ตัดหญ้า",
    "description": "ความเชี่ยวชาญกลุ่มงาน Maid: จัดสวน / ตัดแต่งกิ่ง / ตัดหญ้า",
    "certificationRequired": false
  },
  {
    "id": "sk-58",
    "code": "SK-58",
    "category": "Maid",
    "name": "แม่บ้าน ทำความสะอาด",
    "description": "ความเชี่ยวชาญกลุ่มงาน Maid: แม่บ้าน ทำความสะอาด",
    "certificationRequired": false
  },
  {
    "id": "sk-59",
    "code": "SK-59",
    "category": "Maid",
    "name": "กำจัดปลวก",
    "description": "ความเชี่ยวชาญกลุ่มงาน Maid: กำจัดปลวก",
    "certificationRequired": false
  }
];

export const INITIAL_INSTALLATION_TYPES: InstallationTypeConfig[] = [
  {
    id: 'inst-built-kitchen',
    name: 'งานติดตั้งครัว Built-in Master (ชุดใหญ่)',
    category: 'Built-in Furniture',
    minSkillLevel: 3,
    requiredTeamSize: 3,
    estDurationHours: 6,
    description: 'ประกอบตู้ Built-in, หินท็อปครัว, งานเจาะท่อดูดควัน และปรับระดับบานตู้ไฮกวน',
    badgeColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  },
  {
    id: 'inst-built-closet',
    name: 'งานติดตั้งตู้เสื้อผ้า Walk-in Closet',
    category: 'Built-in Furniture',
    minSkillLevel: 2,
    requiredTeamSize: 2,
    estDurationHours: 4,
    description: 'ติดตั้งโครงตู้เสื้อผ้า Built-in อะลูมิเนียม หน้าบานกระจก และไฟ LED ซ่อนตู้',
    badgeColor: 'bg-purple-50 text-purple-700 border-purple-200',
  },
  {
    id: 'inst-flooring-laminate',
    name: 'งานปูพื้น SPC / Laminate (50-100 ตร.ม.)',
    category: 'Flooring & Tile',
    minSkillLevel: 2,
    requiredTeamSize: 2,
    estDurationHours: 4,
    description: 'ปรับระดับพื้น ปูแผ่นรองกันความชื้น และติดตั้งแผ่น SPC พร้อมบัวพื้นรอบห้อง',
    badgeColor: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  {
    id: 'inst-smart-home',
    name: 'งานติดตั้งระบบ Smart Home & Digital Door Lock',
    category: 'Electrical & Smart Home',
    minSkillLevel: 2,
    requiredTeamSize: 1,
    estDurationHours: 2,
    description: 'เจาะประตูติดตั้ง Digital Lock, สวิตช์ไฟอัจฉริยะ และเซ็ตอัประบบ Gateway',
    badgeColor: 'bg-cyan-50 text-cyan-700 border-cyan-200',
  },
  {
    id: 'inst-aircon-multi',
    name: 'งานติดตั้งเครื่องปรับอากาศ Multi-Split 3 เครื่อง',
    category: 'Air Condition & HVAC',
    minSkillLevel: 3,
    requiredTeamSize: 2,
    estDurationHours: 5,
    description: 'เดินท่อน้ำยาคอมเพรสเซอร์ภายนอก แขวนคอยล์เย็น และทดสอบแรงดันระบบน้ำยา R32',
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  {
    id: 'inst-curtains-motor',
    name: 'งานติดตั้งผ้าม่านมอเตอร์ไฟฟ้า + วอลเปเปอร์',
    category: 'Curtains & Wallpaper',
    minSkillLevel: 1,
    requiredTeamSize: 2,
    estDurationHours: 3,
    description: 'ติดตั้งรางม่านไฟฟ้า ต่อสายสัญญาณ และปูวอลเปเปอร์ไวนิลเกรดพรีเมียม',
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
];

export const SERVICE_ZONES: string[] = INITIAL_ZONES.map((z) => z.name);

export const AVAILABLE_TIME_SLOTS: TimeSlot[] = [
  { id: 'slot-am-1', startTime: '09:00', endTime: '12:00', period: 'Morning' },
  { id: 'slot-pm-1', startTime: '13:00', endTime: '17:00', period: 'Afternoon' },
  { id: 'slot-fd-1', startTime: '09:00', endTime: '17:00', period: 'Full Day' },
];

export const INITIAL_TECHNICIANS: Technician[] = generate200Technicians();

export const INITIAL_BOOKINGS: QueueBooking[] = [
  {
    id: 'bk-1001',
    bookingRef: 'BK-2026-0723-01',
    customerName: 'คุณภิญโญ รัตนประเสริฐ',
    customerPhone: '089-888-7766',
    addressZone: 'Zone 1: กรุงเทพฯ (สุขุมวิท - บางนา - ประเวศ)',
    installationTypeId: 'inst-built-kitchen',
    installationTypeName: 'งานติดตั้งครัว Built-in Master (ชุดใหญ่)',
    requiredSkillLevel: 3,
    assignedTechTeamId: 'tech-01',
    assignedTechTeamName: 'ทีมช่างสมชาย & ทีม (ช่างใหญ่ Built-in)',
    bookingDate: '2026-07-24',
    timeSlot: '09:00 - 17:00 (Full Day)',
    status: 'Dispatched to BuildFlow',
    createdFrom: 'Selling Tools (E-ordering)',
    createdAt: '2026-07-23 08:30',
    branchId: 'br-01',
  },
  {
    id: 'bk-1002',
    bookingRef: 'BK-2026-0723-02',
    customerName: 'คุณสิรินทร์ วงศ์อนันต์',
    customerPhone: '081-333-2211',
    addressZone: 'Zone 2: นนทบุรี (ราชพฤกษ์ - แจ้งวัฒนะ - บางบัวทอง)',
    installationTypeId: 'inst-aircon-multi',
    installationTypeName: 'งานติดตั้งเครื่องปรับอากาศ Multi-Split 3 เครื่อง',
    requiredSkillLevel: 3,
    assignedTechTeamId: 'tech-02',
    assignedTechTeamName: 'ทีมช่างวิชัย อินสทอลเลอร์ (ช่างแอร์ & ไฟฟ้า)',
    bookingDate: '2026-07-24',
    timeSlot: '13:00 - 17:00 (Afternoon)',
    status: 'STS In-Progress',
    createdFrom: 'Selling Tools (E-ordering)',
    createdAt: '2026-07-23 09:15',
    branchId: 'br-03',
  },
  {
    id: 'bk-1003',
    bookingRef: 'BK-2026-0723-03',
    customerName: 'คุณณัฐพล เดชอนันต์',
    customerPhone: '084-777-6655',
    addressZone: 'Zone 1: กรุงเทพฯ (สุขุมวิท - บางนา - ประเวศ)',
    installationTypeId: 'inst-flooring-laminate',
    installationTypeName: 'งานปูพื้น SPC / Laminate (50-100 ตร.ม.)',
    requiredSkillLevel: 2,
    assignedTechTeamId: 'tech-03',
    assignedTechTeamName: 'ทีมช่างประเสริฐการช่าง (ช่างปูพื้น SPC & งานไม้)',
    bookingDate: '2026-07-25',
    timeSlot: '09:00 - 12:00 (Morning)',
    status: 'Scheduled',
    createdFrom: 'COOHOM Direct',
    createdAt: '2026-07-23 10:00',
    branchId: 'br-02',
  },
  {
    id: 'bk-1004',
    bookingRef: 'BK-2026-0723-04',
    customerName: 'คุณพรพิมล เมธากุล',
    customerPhone: '086-111-9900',
    addressZone: 'Zone 4: สมุทรปราการ (เทพารักษ์ - ศรีนครินทร์ - สำโรง)',
    installationTypeId: 'inst-built-closet',
    installationTypeName: 'งานติดตั้งตู้เสื้อผ้า Walk-in Closet',
    requiredSkillLevel: 2,
    assignedTechTeamId: 'tech-05',
    assignedTechTeamName: 'ทีมช่างกิตติพงษ์',
    bookingDate: '2026-07-22',
    timeSlot: '09:00 - 17:00 (Full Day)',
    status: 'Penalty E-CN Issued',
    createdFrom: 'Manual POS',
    createdAt: '2026-07-22 14:00',
    penaltyRef: 'ECN-2026-0722-09',
    branchId: 'br-04',
  },
];

export const INITIAL_PENALTIES: PenaltyRecord[] = [
  {
    id: 'pen-901',
    eCnNumber: 'ECN-2026-0722-09',
    bookingRef: 'BK-2026-0722-04',
    techId: 'tech-05',
    techName: 'ทีมช่างกิตติพงษ์',
    violationType: 'QC Defect / Failed Review',
    fineAmountTHB: 3500,
    scoreDeduction: 25,
    tierImpact: 'ปรับลดจาก Silver -> Cooldown (พักการจ่ายคิวงาน 7 วัน)',
    issuedAt: '2026-07-22 17:30',
    status: 'Active Penalty',
    details: 'งานประกอบโครงตู้ Walk-in Closet ไม่ได้ระดับ ฉากเอียง 5 องศา และบานตู้ตก QC ตรวจพบรอยขูดขีดบนแผงไม้',
  },
  {
    id: 'pen-902',
    eCnNumber: 'ECN-2026-0715-02',
    bookingRef: 'BK-2026-0715-11',
    techId: 'tech-03',
    techName: 'ทีมช่างประเสริฐการช่าง',
    violationType: 'Late Arrival (SLA Breach)',
    fineAmountTHB: 1000,
    scoreDeduction: 10,
    tierImpact: 'หักคะแนน Queue Priority อัตโนมัติ 15%',
    issuedAt: '2026-07-15 11:00',
    status: 'Resolved / Fine Paid',
    details: 'เข้าหน้างานล่าช้ากว่าเวลานัดหมาย 1 ชั่วโมง 45 นาที โดยไม่ได้แจ้งล่วงหน้าผ่านระบบ KANNA/STS',
  },
];

const CORE_USERS: UserAccount[] = [
  {
    id: 'usr-001',
    username: 'sysadmin',
    name: 'คุณชัยวัฒน์ มงคลสุวรรณ',
    email: 'chaiwat.m@vservice.co.th',
    phone: '081-999-8888',
    password: 'Password@123',
    lineId: '@sysadmin_vservice',
    role: 'sys_admin',
    status: 'Active',
    createdAt: '2026-01-01'
  },
  {
    id: 'usr-002',
    username: 'admin_center',
    name: 'คุณอนันต์ ตั้งเจริญ',
    email: 'anan.t@vservice.co.th',
    phone: '089-777-6655',
    password: 'Password@123',
    lineId: '@anan_vservice',
    role: 'admin',
    status: 'Active',
    createdAt: '2026-01-15'
  },
  {
    id: 'usr-003',
    username: 'super_bkk',
    name: 'คุณวรวุฒิ สมบูรณ์',
    email: 'worawut.s@vservice.co.th',
    phone: '086-555-4433',
    password: 'Password@123',
    lineId: '@worawut_super',
    role: 'supervisor',
    status: 'Active',
    branchId: 'br-01',
    branchName: 'สาขาพระราม 9',
    createdAt: '2026-02-01'
  },
  {
    id: 'usr-005',
    username: 'cs_rama9',
    name: 'คุณกนกวรรณ ใจดี (CS พระราม 9)',
    email: 'kanokwan.j@vservice.co.th',
    phone: '084-222-3344',
    password: 'Password@123',
    lineId: '@cs_rama9',
    role: 'storecs',
    status: 'Active',
    branchId: 'br-01',
    branchName: 'สาขาพระราม 9',
    createdAt: '2026-03-01'
  },
  {
    id: 'usr-006',
    username: 'cust_pinyo',
    name: 'คุณภิญโญ รัตนประเสริฐ',
    email: 'pinyo.r@gmail.com',
    phone: '089-888-7766',
    password: 'Password@123',
    lineId: '@pinyo_r',
    role: 'customer',
    status: 'Active',
    createdAt: '2026-07-20'
  }
];

const techUserAccounts: UserAccount[] = generate200Technicians().map((tech) => {
  const techUsername = `tech_${tech.code.toLowerCase().replace(/[^a-z0-9]/g, '')}`;
  const techLineId = `@tech_${tech.code.toLowerCase().replace(/[^a-z0-9]/g, '')}`;
  return {
    id: `usr-tech-${tech.id}`,
    username: techUsername,
    name: tech.name,
    email: `${techUsername}@vservice-tech.co.th`,
    phone: tech.phone || '081-000-0000',
    password: 'p123',
    lineId: techLineId,
    role: 'technician',
    status: 'Active',
    createdAt: '2026-02-10'
  };
});

export const INITIAL_USERS: UserAccount[] = [
  ...CORE_USERS,
  ...techUserAccounts
];


export const INITIAL_STANDARD_COSTS: StandardCostItem[] = [
  {
    "id": "std-cost-001",
    "sku": "SKU-STD-001",
    "group": "Group",
    "productCategory": "Product",
    "serviceType": "service type",
    "productDetail": "Product detail",
    "description": "Description",
    "unit": "Unit",
    "gpPercent": 0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "Cost Center",
    "retention": "Retention",
    "remark": "Remark",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-002",
    "sku": "SKU-STD-002",
    "group": "ค่าบริการ M",
    "productCategory": "แอร์",
    "serviceType": "บริการล้าง",
    "productDetail": "",
    "description": "ค่าบริการ M-บริการล้าง แอร์",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 500.0,
    "costPremium": 500.0,
    "priceStandard": 650.0,
    "pricePremium": 650.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "SKU นี้ใช้ได้เฉพาะ QC เท่านั้น \nหรือต้องได้รับการอนุมัติก่อน",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-003",
    "sku": "SKU-STD-003",
    "group": "ค่าบริการ M",
    "productCategory": "แม่บ้าน",
    "serviceType": "ทำความสะอาด",
    "productDetail": "",
    "description": "ค่าบริการ M-ทำความสะอาด แม่บ้าน",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 600.0,
    "costPremium": 600.0,
    "priceStandard": 780.0,
    "pricePremium": 780.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-004",
    "sku": "SKU-STD-004",
    "group": "ค่าบริการ Q",
    "productCategory": "เฟอร์นิเจอร์",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ Q-ติดตั้ง เฟอร์นิเจอร์",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 700.0,
    "costPremium": 700.0,
    "priceStandard": 910.0,
    "pricePremium": 910.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-005",
    "sku": "SKU-STD-005",
    "group": "ค่าบริการ M",
    "productCategory": "ปลวกและแมลง",
    "serviceType": "ทำความสะอาด",
    "productDetail": "",
    "description": "ค่าบริการ M-ทำความสะอาด ปลวกและแมลง",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 500.0,
    "costPremium": 500.0,
    "priceStandard": 650.0,
    "pricePremium": 650.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-006",
    "sku": "SKU-STD-006",
    "group": "ค่าบริการ Q",
    "productCategory": "แอร์",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ Q-ติดตั้ง แอร์",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 600.0,
    "costPremium": 600.0,
    "priceStandard": 780.0,
    "pricePremium": 780.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-007",
    "sku": "SKU-STD-007",
    "group": "ค่าบริการ Q",
    "productCategory": "อุปกรณ์",
    "serviceType": "งานเพิ่มงานบริการ",
    "productDetail": "",
    "description": "ค่าบริการ Q-งานเพิ่มงานบริการ อุปกรณ์",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 700.0,
    "costPremium": 700.0,
    "priceStandard": 910.0,
    "pricePremium": 910.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-008",
    "sku": "SKU-STD-008",
    "group": "ค่าบริการ Q",
    "productCategory": "เครื่องใช้ไฟฟ้า",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ Q-ติดตั้ง เครื่องใช้ไฟฟ้า",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 500.0,
    "costPremium": 500.0,
    "priceStandard": 650.0,
    "pricePremium": 650.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-009",
    "sku": "SKU-STD-009",
    "group": "ค่าบริการ Q",
    "productCategory": "ปั๊มแท็งก์",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ Q-ติดตั้ง ปั๊มแท็งก์",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 600.0,
    "costPremium": 600.0,
    "priceStandard": 780.0,
    "pricePremium": 780.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-010",
    "sku": "SKU-STD-010",
    "group": "ค่าบริการ Q",
    "productCategory": "พัดลมดูดอากาศ",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ Q-ติดตั้ง พัดลมดูดอากาศ",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 700.0,
    "costPremium": 700.0,
    "priceStandard": 910.0,
    "pricePremium": 910.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-011",
    "sku": "SKU-STD-011",
    "group": "ค่าบริการ Q",
    "productCategory": "ลามิเนตและกระเบื้องยาง",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ Q-ติดตั้ง ลามิเนตและกระเบื้องยาง",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 500.0,
    "costPremium": 500.0,
    "priceStandard": 650.0,
    "pricePremium": 650.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-012",
    "sku": "SKU-STD-012",
    "group": "ค่าบริการ Q",
    "productCategory": "กระเบื้อง",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ Q-ติดตั้ง กระเบื้อง",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 600.0,
    "costPremium": 600.0,
    "priceStandard": 780.0,
    "pricePremium": 780.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-013",
    "sku": "SKU-STD-013",
    "group": "ค่าบริการ Q",
    "productCategory": "สุขภัณฑ์ห้องน้ำ",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ Q-ติดตั้ง สุขภัณฑ์ห้องน้ำ",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-014",
    "sku": "SKU-STD-014",
    "group": "ค่าบริการ Q",
    "productCategory": "ประตูและหน้าต่าง",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ Q-ติดตั้ง ประตูและหน้าต่าง",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-015",
    "sku": "SKU-STD-015",
    "group": "ค่าบริการ M",
    "productCategory": "หญ้าสนาม",
    "serviceType": "ตกแต่ง",
    "productDetail": "ความสูงไม่เกิน15CM.>300 ตร.ม.ขึ้นไป",
    "description": "ค่าบริการ M-ตกแต่ง หญ้าสนาม ความสูงไม่เกิน15CM.>300 ตร.ม.ขึ้นไป",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-016",
    "sku": "SKU-STD-016",
    "group": "0",
    "productCategory": "0",
    "serviceType": "0",
    "productDetail": "",
    "description": "0",
    "unit": "0",
    "gpPercent": 0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-017",
    "sku": "SKU-STD-017",
    "group": "ค่าบริการ R",
    "productCategory": "งานโครงสร้าง",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง งานโครงสร้าง",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "SKU นี้ใช้ได้เฉพาะ QC เท่านั้น \nหรือต้องได้รับการอนุมัติก่อน",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-018",
    "sku": "SKU-STD-018",
    "group": "ค่าบริการ R",
    "productCategory": "ทาสี",
    "serviceType": "ทาสี",
    "productDetail": "",
    "description": "ค่าบริการ R-ทาสี  ทาสี",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-019",
    "sku": "SKU-STD-019",
    "group": "ค่าบริการ R",
    "productCategory": "เฟอร์นิเจอร์",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง เฟอร์นิเจอร์",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-020",
    "sku": "SKU-STD-020",
    "group": "ค่าบริการ R",
    "productCategory": "กระเบื้อง",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง กระเบื้อง",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-021",
    "sku": "SKU-STD-021",
    "group": "ค่าบริการ R",
    "productCategory": "งานห้องน้ำ",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง งานห้องน้ำ",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-022",
    "sku": "SKU-STD-022",
    "group": "ค่าบริการ R",
    "productCategory": "ระบบไฟฟ้า",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง ระบบไฟฟ้า",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-023",
    "sku": "SKU-STD-023",
    "group": "ค่าบริการ R",
    "productCategory": "พัดลมดูดอากาศ",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง พัดลมดูดอากาศ",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-024",
    "sku": "SKU-STD-024",
    "group": "ค่าบริการ R",
    "productCategory": "ครัวปูน",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง ครัวปูน",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-025",
    "sku": "SKU-STD-025",
    "group": "ค่าบริการ R",
    "productCategory": "เครื่องใช้ไฟฟ้า",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง เครื่องใช้ไฟฟ้า",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-026",
    "sku": "SKU-STD-026",
    "group": "ค่าบริการ R",
    "productCategory": "ปั๊มแท็งก์",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง ปั๊มแท็งก์",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-027",
    "sku": "SKU-STD-027",
    "group": "ค่าบริการ R",
    "productCategory": "ลามิเนตและกระเบื้องยาง",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง ลามิเนตและกระเบื้องยาง",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 0,
    "costPremium": 0,
    "priceStandard": 0,
    "pricePremium": 0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-028",
    "sku": "SKU-STD-028",
    "group": "ค่าบริการ R",
    "productCategory": "ประตูและหน้าต่าง",
    "serviceType": "ติดตั้ง",
    "productDetail": "",
    "description": "ค่าบริการ R-ติดตั้ง ประตูและหน้าต่าง",
    "unit": "EACH",
    "gpPercent": -1.0,
    "costStandard": 700.0,
    "costPremium": 700.0,
    "priceStandard": 910.0,
    "pricePremium": 910.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  },
  {
    "id": "std-cost-029",
    "sku": "SKU-STD-029",
    "group": "0",
    "productCategory": "0",
    "serviceType": "0",
    "productDetail": "",
    "description": "0",
    "unit": "0",
    "gpPercent": 0,
    "costStandard": 350.0,
    "costPremium": 350.0,
    "priceStandard": 420.0,
    "pricePremium": 420.0,
    "costCenter": "21713",
    "retention": "",
    "remark": "",
    "updatedAt": "2026-08-02"
  }
];
